---
title: Mouse.isPressed()
---




= Mouse.isPressed()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Checkt den aktuellsten Status des Mausbuttons und liefert zurück, ob dieser gedrückt ist.
[%hardbreaks]


[float]
=== Syntax
`Mouse.isPressed()` +
`Mouse.isPressed(button)`

[float]
=== Parameter
Default wird der linke Mausbutton gecheckt.

`button`: Welcher Mausbutton gecheckt werden soll - `char`

* `MOUSE_LEFT (default)`

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

[float]
=== Rückgabewert
`boolean` : Ob ein Mausbutton gedrückt ist oder nicht.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Setzt den Mausbutton und löst ihn wieder abhängig vom gedrückten Schalter an Pin 2 und 3. Speichert dabei den Status der Maus.

[source,arduino]
----
#include <Mouse.h>

void setup() {
  // Der Schalter, der den Mauszeigerdruck startet: Pin 2
  pinMode(2, INPUT);
  // Der Schalter, der den Mauszeigerdruck beendet: Pin 3
  pinMode(3, INPUT);
  //Starte serielle Kommunikation mit dem Computer
  Serial.begin(9600);
  // Initialisiere die Maus-Bibliothek:
  Mouse.begin();
}

void loop() {
  // Eine Variable, um den aktuellen Status der Maus zu speichern
  int mouseState = 0;
  // Wenn Pin 2 HIGH ist (Schalter geschlossen), drücke den Mausbutton und halte ihn. Speichere den Status der Maus in die Variable.
  if (digitalRead(2) == HIGH) {
    Mouse.press();
    mouseState=Mouse.isPressed();
  }
  // Wenn Pin 3 HIGH ist (Schalter geschlossen), löse den gedrückten Mausbutton. Speichere den Status der Maus in die Variable.
  if (digitalRead(3) == HIGH) {
    Mouse.release();
    mouseState=Mouse.isPressed();
  }
  // Gib den aktuellen Status der Maus aus
  Serial.println(mouseState);
  delay(10);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../mouseclick[Mouse.click()]
* #SPRACHE# link:../mouseend[Mouse.end()]
* #SPRACHE# link:../mousemove[Mouse.move()]
* #SPRACHE# link:../mousepress[Mouse.press()]
* #SPRACHE# link:../mouserelease[Mouse.release()]

--
// SEE ALSO SECTION ENDS
