---
title: Mouse.release()
---




= Mouse.release()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Löst den zuletzt per link:../mousepress[Mouse.press()] gedrückten Button. Der Defaultbutton von `Mouse.release()` ist der linke Mausbutton.
[%hardbreaks]


[float]
=== Syntax
`Mouse.release();` +
`Mouse.release(button);`

[float]
=== Parameter
`button`: Welcher Mausbutton gelöst werden soll - Char

* `MOUSE_LEFT` (default)

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Setzt den Mausbutton und löst ihn wieder abhängig vom gedrückten Schalter an Pin 2 und 3.

[source,arduino]
----
#include <Mouse.h>

void setup(){
  // Der Schalter, der den Mauszeigerdruck startet: Pin 2
  pinMode(2,INPUT);
  // Der Schalter, der den Mauszeigerdruck beendet: Pin 3
  pinMode(3,INPUT);
  // Initialisiere die Maus-Bibliothek:
  Mouse.begin();
}

void loop(){
  // Wenn Pin 2 HIGH ist (Schalter geschlossen), drücke den Mausbutton und halte ihn.
  if(digitalRead(2) == HIGH){
    Mouse.press();
  }
  // Wenn Pin 3 HIGH ist (Schalter geschlossen), löse den gedrückten Mausbutton.
  if(digitalRead(3) == HIGH){
    Mouse.release();
  }
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn das `Mouse.release()`-Kommando benutzt wird, übernimmt der Arduino die Tastatur! Stelle sicher, dass du Kontrolle über die Tastatur hast, bevor du das Kommando verwendest.
Ein Button, um die Funktion notfalls zu sperren, ist sinnvoll.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE# link:../mouseclick[Mouse.click()]
* #LANGUAGE# link:../mouseend[Mouse.end()]
* #LANGUAGE# link:../mousemove[Mouse.move()]
* #LANGUAGE# link:../mousepress[Mouse.press()]
* #LANGUAGE# link:../mouseispressed[Mouse.isPressed()]

--
// SEE ALSO SECTION ENDS
