---
title: Mouse.end()
---




= Mouse.end()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Stoppt die Emulation der Maus auf dem verbundenen Computer. Um die Maus zu starten, benutze link:../mousebegin[Mouse.begin()].
[%hardbreaks]


[float]
=== Syntax
`Mouse.end()`


[float]
=== Parameter
Keine.


[float]
=== Rückgabewert
Ninhts.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Sendet einen linken Mausclick, wenn der Button gedrückt wird und beendet die Emulation anschließend.

[source,arduino]
----
#include <Mouse.h>

void setup() {
  // Setze Pin 2 als Inputpin
  pinMode(2, INPUT);
  // Initialisiere die Maus-Bibliothek
  Mouse.begin();
}

void loop() {
  // Wenn der Button an Pin 2 gedrückt wird, sende einen linken Mausklick
  // und beende die Emulation wieder.
  if (digitalRead(2) == HIGH){
    Mouse.click();
    Mouse.end();
  }
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../mouseclick[Mouse.click()]
* #SPRACHE# link:../mousemove[Mouse.move()]
* #SPRACHE# link:../mousepress[Mouse.press()]
* #SPRACHE# link:../mouserelease[Mouse.release()]
* #SPRACHE# link:../mouseispressed[Mouse.isPressed()]

--
// SEE ALSO SECTION ENDS
