---
title: Mouse.click()
---




= Mouse.click()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Sendet einen Mausklick an den verbundenen Computer. Dies ist das Gleiche wie den Button zu drücken und sofort wieder loszulassen.

Der Defaultbutton von `Mouse.click()` ist der linke Mausbutton.
[%hardbreaks]


[float]
=== Syntax
`Mouse.click()` +
`Mouse.click(button)`


[float]
=== Parameter
`button`: Welcher Mausbutton gedrückt werden soll - `char`

* `MOUSE_LEFT` (default)
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Sendet einen linken Mausklick, wenn der Button gedrückt wird.

[source,arduino]
----
#include <Mouse.h>

void setup() {
  // Setze Pin 2 als Inputpin
  pinMode(2,INPUT);
  //Initialisiere die Maus-Bibliothek
  Mouse.begin();
}

void loop() {
  // Sende einen linken Mausklick, wenn der Button gedrückt wird
  if (digitalRead(2) == HIGH){
    Mouse.click();
  }
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn das `Mouse.click()`-Kommando benutzt wird, übernimmt der Arduino die Tastatur! Stelle sicher, dass du Kontrolle über die Tastatur hast, bevor du das Kommando verwendest.
Ein Button, um die Funktion notfalls zu sperren, ist sinnvoll.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE# link:../mouseend[Mouse.end()]
* #LANGUAGE# link:../mousemove[Mouse.move()]
* #LANGUAGE# link:../mousepress[Mouse.press()]
* #LANGUAGE# link:../mouserelease[Mouse.release()]
* #LANGUAGE# link:../mouseispressed[Mouse.isPressed()]

--
// SEE ALSO SECTION ENDS
