---
title: digitalRead()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= digitalRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Liest einen Wert von einem vorgegebenen Digitalpin ein, entweder link:../../variables/constants/constants/[HIGH] oder link:../../variables/constants/constants/[LOW].
[%hardbreaks]


[float]
=== Syntax
`digitalRead(pin)`


[float]
=== Parameter
`pin`: Die Nummer des Digitalpins, die gelesen werden soll.

[float]
=== Gibt zurück
link:../../variables/constants/constants/[HIGH] oder link:../../variables/constants/constants/[LOW]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Setzt pin 13 auf den gleichen Wert wie Pin 7, welcher als Eingang definiert ist.

//[source,arduino]
----
int ledPin = 13;   // LED verbunden auf Digitalpin 13
int inPin = 7;     // Button verbunden auf Digitalpin 7 
int val = 0;       // Variable, um den gelesenen Wert zu speichern

void setup()
{
  pinMode(ledPin, OUTPUT);      // Setzt den Digitalpin 13 als Outputpin
  pinMode(inPin, INPUT);        // Setzt den Digitalpin 7 als Intputpin
}

void loop()
{
  val = digitalRead(inPin);     // Liest den Inputpin
  digitalWrite(ledPin, val);    // Setzt die LED auf den Wert des Buttons
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn der Pin nicht mit irgendetwas verbunden ist, kann ``digitalRead()`` entweder link:../../variables/constants/constants/[HIGH] oder link:../../variables/constants/constants/[LOW] (das passiert völlig zufällig) zurückgeben.

Die analogen Inputpins können als Digitalpins verwendet werden mit den Namen A0, A1, etc.
--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #Beispiel#-Tutorial: (http://arduino.cc/en/Tutorial/DigitalPins[Digitale Pins])

--
// SEE ALSO SECTION ENDS
