---
title: digitalWrite()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= digitalWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Schreibt einen `HIGH`- oder `LOW`-Wert auf einen Digitalpin.

Wenn der Pin mit `pinMode()` als Outputpin gesetzt wird, wird die Spannung auf den Wert 5V (oder 3,3V) für `HIGH` gesetzt, 0V für `LOW`. Es wird empfohlen, den Pin mit `pinMode()` auf `INPUT_PULLUP` zu setzen, um den internen Pull-Up-Widerstand zu nutzen. Für mehr Informationen siehe: http://arduino.cc/en/Tutorial/DigitalPins[Tutorial zu Digitalpins].
[%hardbreaks]

Wenn du `pinMode()` nicht auf `OUTPUT` setzt, aber eine LED auf den Pin anschließt, kann die LED mit `digitalWrite(HIGH)` gedimmt erscheinen. Wenn `pinMode()` nicht explicit gesetzt wird, verwendet `digitalWrite()` den Pull-Up-Widerstand, der als eine Art großer spannungslimitierender Widerstand wirkt.
[%hardbreaks]

[float]
=== Syntax
`digitalWrite(pin, value)`


[float]
=== Parameter
`pin`: Die Pinnummer.

`value`: `HIGH` oder `LOW`

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code deklariert Digitalpin 13 als `OUTPUT` und alterniert auf diesem Pin von `HIGH` auf `LOW` mit einem Abstand von einer Sekunde.

[source,arduino]
----
void setup() {
  pinMode(13, OUTPUT); // Setzt den Digitalpin 13 als Outputpin
}

void loop() {
  digitalWrite(13, HIGH); // Setzt den Digitalpin 13 auf HIGH = "Ein"
  delay(1000);            // Wartet eine Sekunde
  digitalWrite(13, LOW);  // Setzt den Digitalpin 13 auf LOW = "Aus"
  delay(1000);            // Wartet eine Sekunde
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Die analogen Inputpins können als Digitalpins verwendet werden mit den Namen A0, A1, etc. Die Ausnahme sind der Arduino Nano, Pro Mini, und die Arduino Mini-Pins A6 und A7, welche nur
als analoge Inputs genutzt werden können.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL#-Tutorial: (http://arduino.cc/en/Tutorial/DigitalPins[Beschreibung der digitalen Pins^])

--
// SEE ALSO SECTION ENDS
