---
title: pinMode()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= pinMode()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Konfiguriert den spezifizierten Pin als Input oder Output. Für mehr Informationen siehe: http://arduino.cc/en/Tutorial/DigitalPins[Tutorial zu Digitalpins].
[%hardbreaks]
Seit Arduino 1.0.1 ist es möglich, den internen Pull-Up-Widerstand mit dem Modus `INPUT_PULLUP` zu setzen. Der `INPUT`-Modus deaktiviert den internen Pull-Up-Widerstand komplett.
[%hardbreaks]


[float]
=== Syntax
`pinMode(pin, mode)`

[float]
=== Parameter
`pin`: Die Pinnummer, auf der der Pinmodus gesetzt werden soll.

`mode`: `INPUT`, `OUTPUT` oder `INPUT_PULLUP`. (Für mehr Informationen siehe: http://arduino.cc/en/Tutorial/DigitalPins[Tutorial zu Digitalpins].)

//Check how to add links

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
Der Code deklariert Digitalpin 13 als `OUTPUT` und alterniert auf diesem Pin von `HIGH` auf `LOW` mit einem Abstand von einer Sekunde.

//[source,arduino]
----
void setup()
{
  pinMode(13, OUTPUT);          // Setzt den Digitalpin 13 als Outputpin
}

void loop()
{
  digitalWrite(13, HIGH);       // Setzt den Digitalpin 13 auf HIGH = "Ein"
  delay(1000);                  // Wartet eine Sekunde
  digitalWrite(13, LOW);        // Setzt den Digitalpin 13 auf LOW = "Aus"
  delay(1000);                  // Wartet eine Sekunde
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Die analogen Inputpins können als Digitalpins verwendet werden mit den Namen A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #Beispiel# http://arduino.cc/en/Tutorial/DigitalPins[Beschreibung der Pins auf dem Arduino-Board^]

--
// SEE ALSO SECTION ENDS
