---
title: sizeof()
categories: [ "Variables" ]
subCategories: [ "Utilities" ]
---





= sizeof


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`sizeof` gibt die Anzahl an Bytes in einem Variablentyp oder die Anzahl an Bytes eines Arrays zurück.
[%hardbreaks]


[float]
=== Syntax
`sizeof(variable)`


[float]
=== Parameter
`variable`: Jeder beliebige Variablentyp oder auch ein Array (z.B. int, float, byte)

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der `sizeof`-Operator ist nützlich, um mit Arrays (wie z.B. Strings) umzugehen. Dort ist es Standard, dass die Größe des Arrays sich ändert, ohne
dass das ganze restliche Programm umgeschrieben werden muss.

Das Programm gibt einen Text zeichenweise aus. Versuche, den Text zu ändern, das Programm wird weiter funktionieren.

[source,arduino]
----
// Definiere Text und Zählervariable
char myStr[] = "this is a test";

void setup() {
  // Initialisiere seriellen Port
  Serial.begin(9600);
}

void loop() {
  // Laufe über das Array (den String), egal, wie lange dieser ist
  for (byte i = 0; i < sizeof(myStr) - 1; i++) {
	// Gib die Zeichennummer als Dezimalzahl aus
    Serial.print(i, DEC);
	// Gib ein Gleichheitszeichen aus
    Serial.print(" = ");
	// Gib das Zeichen des Strings an Stelle "i" aus
    Serial.write(myStr[i]);
	// Schreibe eine neue Zeile
    Serial.println();
  }
  delay(5000); // Warte 5 Sekunden
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
`sizeof` gibt die Anzahl an Bytes zurück. Für Arrays größerer Variablentypen, wie z.B. Integer, sieht die Schleife wie folgt aus:

[source,arduino]
----
int myValues[] = {123, 456, 789};
// Diese for-Schleife funktioniert ordnungsgemäß mit einem Array eines beliebigen Typs und jeder Größe
for (byte i = 0; i < (sizeof(myValues)/sizeof(myValues[0])); i++) {
  // Tue etwas mit myValues[i]
}
----

Beachte zusätzlich, dass ein richtig formattierter String mit dem `NULL`-Symbol beendet wird, also dem ASCII-Zeichen mit Nummer 0.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
