---
title: double
categories: [ "Variables" ]
subCategories: [ "Datentypen" ]
---

= double

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Fließkommazahl mit doppelter Genauigkeit. Auf dem Uno und anderen ATMEGA-basierten Boards belegt dies 4 Bytes.
Das heißt, die double-Implementierung entspricht genau dem float, ohne dass die Genauigkeit zunimmt.

Auf dem Arduino Due haben doubles eine Genauigkeit von 8 Byte (64 Bit).
[%hardbreaks]


[float]
=== Syntax
`double var = val;`


[float]
=== Parameter
`var`: Variablenname +
`val`: Der Wert, der der Variablen zugewiesen wird

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--


[float]
=== Anmerkungen und Warnungen
Benutzer, die sich Code aus anderen Quellen leihen, der double-Variablen enthält, möchten möglicherweise den Code untersuchen, um zu sehen,
ob sich die implizierte Genauigkeit von der tatsächlich bei ATMEGA-basierten Arduinos erreichten unterscheidet.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
