---
title: float
categories: [ "Variables" ]
subCategories: [ "Datentypen" ]
---

= float

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Datentyp für Fließkommazahlen, eine Zahl mit Dezimalpunkt.
Fließkommazahlen werden häufig zur Annäherung an analoge und kontinuierliche Werte verwendet, da sie eine höhere Auflösung als ganze Zahlen haben.
Fließkommazahlen können bis zu 3.4028235E+38 und bis zu -3.4028235E+38 betragen. Sie werden als 32 Bit (4 Byte) Informationen gespeichert.

Floats haben eine Genauigkeit von nur 6-7 Dezimalstellen. Das bedeutet die Gesamtzahl der Ziffern, nicht die Zahl rechts vom Dezimalpunkt.
Im Gegensatz zu anderen Plattformen, bei denen du durch die Verwendung eines doubles (z. B. bis zu 15 Ziffern) eine höhere Genauigkeit erzielen kannst, hat double auf dem Arduino die gleiche Größe wie float.

Fließkommazahlen sind nicht genau und können beim Vergleich zu seltsamen Ergebnissen führen. Zum Beispiel kann 6.0 / 3.0 nicht gleich 2.0 sein.
Du solltest stattdessen überprüfen, ob der absolute Wert der Differenz zwischen den Zahlen geringer als eine kleine Zahl ist.

Die Gleitkomma-Mathematik ist bei Berechnungen auch viel langsamer als die Ganzzahl-Mathematik.
Es sollte also vermieden werden, wenn beispielsweise eine Schleife für eine kritische Timing-Funktion mit Höchstgeschwindigkeit laufen muss.
Programmierer gehen oft etwas in die Länge und konvertieren Gleitkomma-Berechnungen in Ganzzahl-Mathematik, um die Geschwindigkeit zu erhöhen.

Wenn du mit floats rechnest, musst du ein Dezimalzeichen hinzufügen, andernfalls wird es als int behandelt. Siehe die link:../../constants/floatingpointconstants[Fließpunkt]-Konstanten-Seite für weitere Informationen.
[%hardbreaks]

[float]
=== Syntax
`float var=val;`

[float]
=== Parameter
`var`: Variablenname +
`val`: Der Wert, der der Variablen zugewiesen wird
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
  float myfloat;
  float sensorCalbrate = 1.117;

  int x;
  int y;
  float z;

  x = 1;
  y = x / 2;          // y enthält jetzt 0, ints können keine Brüche enthalten
  z = (float)x / 2.0; // z enthält jetzt .5 (Du musst 2.0 verwenden, nicht 2)
----


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
