---
title: int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= int

// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Ganzzahlen sind der primäre Datentyp für die Nummernspeicherung.

Auf dem Arduino Uno (und anderen ATmega-basierten Boards) speichert ein `int` einen 16-Bit-Wert (2 Byte).
Dies ergibt einen Bereich von -32,768 bis 32,767 (Minimalwert -2^15 und Maximalwert (2^15) - 1).
Auf den Arduino Due- und SAMD-basierten Boards (wie MKR1000 und Zero) speichert ein `int` einen 32-Bit-Wert (4 Byte).
Dies ergibt einen Bereich von -2,147,483,648 to 2,147,483,647 (Minimalwert -2^31 und Maximalwert (2^31) - 1).

Int speichert negative Zahlen mit einer Technik namens (https://de.wikipedia.org/wiki/Zweierkomplement[Zweierkomplement]).
Das höchste Bit, manchmal auch als "Vorzeichen" bezeichnet, kennzeichnet die Zahl als negative Zahl. Die restlichen Bits werden invertiert und 1 wird hinzugefügt.

Der Arduino kümmert sich um den Umgang mit negativen Zahlen für dich, damit arithmetische Operationen auf die erwartete Weise transparent arbeiten.
Es kann unerwartete Komplikationen im Umgang mit dem link:../../../structure/bitwise-operators/bitshiftright[Rechten Bitshift-Operator] (`>>`) geben.
[%hardbreaks]


[float]
=== Syntax
`int var = val`


[float]
=== Parameter
`var`: Variablenname. +
`val`: Der Wert, der der Variablen zugewiesen wird.
[%hardbreaks]
--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄
Dieser Code erstellt eine Ganzzahl namens 'countUp', die anfänglich als Zahl 0 (Null) festgelegt wird. Der Wert der Variable steigt in jeder Schleife um 1 (eins) und wird auf dem seriellen Monitor angezeigt.

[source,arduino]
----
int countUp = 0; // Erstellt eine variable Ganzzahl mit dem Namen 'countUp'

void setup() {
  Serial.begin(9600); // Verwende die serielle Schnittstelle, um die Nummer auszugeben
}

void loop() {
  countUp++;               // Fügt der countUp-Variable in jeder Schleife 1 hinzu
  Serial.println(countUp); // Gibt den aktuellen Stand von countUp aus
  delay(1000);
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn vorzeichenbehaftete Variablen ihre maximale oder minimale Kapazität überschreiten, _laufen sie über_ (Overflow).
Das Ergebnis eines Überlaufs ist unvorhersehbar, daher sollte dies vermieden werden.
Ein typisches Symptom für einen Überlauf ist die Variable, die von ihrer maximalen Kapazität auf das Minimum "umgedreht" wird oder umgekehrt, dies ist jedoch nicht immer der Fall.
Wenn du dieses Verhalten wünscht, verwende `link:../unsignedint[unsigned int]`.


--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../constants/integerconstants[Ganzzahlkonstanten]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
