---
title: long
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= long

// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Long-Variablen sind Variablen mit erweiterter Größe für die Nummernspeicherung und speichern 32 Bit (4 Byte), von -2,147,483,648 bis 2,147,483,647.

Wenn du mit ganzzahligen Zahlen rechnest, muss mindestens einer der Werte vom Typ `long` sein, entweder ein Integer gefolgt von einem L oder eine long-Variable. Dadurch wird eine Long-Zahl erzwungen.
Siehe auch die link:../../constants/integerconstants[Ganzzahlkonstanten]-Seite für mehr Details.
[%hardbreaks]


[float]
=== Syntax
`long var = val`


[float]
=== Beschreibung
`var`: Variablenname. +
`val`: Der Wert, der der Variablen zugewiesen wird.
[%hardbreaks]
--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
long speedOfLight_km_s = 300000L; // Auf der Ganzzahlkonstanten-Seite findest du Erläuterungen zu dem 'L'.
----

--
// HOW-TO-USE-ABSCHNITT ENDET

// SIEHE-AUCH-ABSCHNITT SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../constants/integerconstants[Ganzzahlkonstanten]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
