---
title: long
categories: [ "Variables" ]
subCategories: [ "Datentypen" ]
---

= long

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Long-Variablen sind Variablen mit erweiterter Größe für die Nummernspeicherung und speichern 32 Bit (4 Byte), von -2,147,483,648 bis 2,147,483,647.

Wenn du mit ganzzahligen Zahlen rechnest, muss mindestens eine der Zahlen von einem L gefolgt werden, wodurch eine long-Zahl erzwungen wird.
Siehe auch die link:../../constants/integerconstants[Ganzzahlkonstanten]-Seite für mehr Details.
[%hardbreaks]

[float]
=== Syntax
`long var = val`

[float]
=== Parameter
`var`: Variablenname +
`val`: Der Wert, der der Variablen zugewiesen wird
[%hardbreaks]
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
long speedOfLight = 186000L; // Auf der Ganzzahlkonstanten-Seite findest du Erläuterungen zu dem 'L'.
----

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../constants/integerconstants[Ganzzahlkonstanten]

--
// SEE ALSO SECTION ENDS
