---
title: "String()"
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= String()

// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Erstellt eine Instanz der `String`-Klasse. Es gibt mehrere Versionen, die Strings aus verschiedenen Datentypen erstellen (d. h. als Zeichenfolgen formatieren), darunter:

* Eine konstante Zeichenfolge in Anführungszeichen (d. h. ein Char-Array)
* Ein einzelnes konstantes Zeichen in einfachen Anführungszeichen
* Eine andere Instanz des `String`-Objekts
* Ein konstanter `int` oder `long int`
* Ein konstanter `int` oder `long int`, der eine angegebene Basis verwendet
* Eine konstante `int` oder `long int` Variable
* Eine konstante `int` oder `long int` Variable, die eine angegebene Basis verwendet
* Ein `float` oder `double` mit einer bestimmten Anzahl Dezimalstellen

Beim Konstruieren einer Zeichenfolge aus einer Zahl wird eine Zeichenfolge erstellt, die die ASCII-Darstellung dieser Zahl enthält. Der Standard ist also Basis zehn:
[source,arduino]
----
String thisString = String(13);
----
Gibt den `String` "13" zurück. Du kannst jedoch auch andere Basen verwenden. Zum Beispiel:


[source,arduino]
----
String thisString = String(13, HEX);
----

Gibt den String "D" zurück. Dies ist die hexadezimale Darstellung des Dezimalwerts 13. Oder, wenn du das Binärformat bevorzugst:

[source,arduino]
----
String thisString = String(13, BIN);
----

Gibt den String "1101" zurück. Das ist die binäre Darstellung von 13.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
String(val)
String(val, base)
String(val, decimalPlaces)
----

[float]
=== Parameter
`val`:  Eine Variable, die als `String` formatiert werden soll. Erlaubte Datentypen: `string`, `char`, `byte`, `int`, `long`, `unsigned int`, `unsigned long`, `float`, `double`. +
`base` (Optional): Die Basis, in der ein ganzzahliger Wert formatiert werden soll. +
`decimalPlaces` (*Nur, wenn val `float` oder `double` ist*): Die gewünschten Dezimalstellen.

[float]
=== Rückgabewert
Eine Instanz der `String`-Klasse.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
Alle folgenden Angaben sind gültige Deklarationen für Strings.
[source,arduino]
----
String stringOne = "Hello String";                        // Ein konstanter String
String stringOne =  String('a');                          // Konvertieren eines konstanten char in einen String
String stringTwo =  String("This is a string");           // Konvertieren eines konstanten String in ein String-Objekt
String stringOne =  String(stringTwo + " with more");     // Zwei Strings konkatenieren
String stringOne =  String(13);                           // Ein konstanter int
String stringOne =  String(analogRead(0), DEC);           // Ein int mit einer Basis
String stringOne =  String(45, HEX);                      // Ein int mit einer Basis (Hexadezimal)
String stringOne =  String(255, BIN);                     // Ein int mit einer Basis (Binär)
String stringOne =  String(millis(), DEC);                // Ein long mit einer Basis
String stringOne =  String(5.698, 3);                     // Ein float mit Dezimalstellen
----

--
// HOW-TO-USE-ABSCHNITT ENDET


[float]
=== Funktionen

[role="language"]
* #SPRACHE# link:../string/functions/charat[charAt()]
* #SPRACHE# link:../string/functions/compareto[compareTo()]
* #SPRACHE# link:../string/functions/concat[concat()]
* #SPRACHE# link:../string/functions/c_str[c_str()]
* #SPRACHE# link:../string/functions/endsWith[endsWith()]
* #SPRACHE# link:../string/functions/equals[equals()]
* #SPRACHE# link:../string/functions/equalsignorecase[equalsIgnoreCase()]
* #SPRACHE# link:../string/functions/getbytes[getBytes()]
* #SPRACHE# link:../string/functions/indexof[indexOf()]
* #SPRACHE# link:../string/functions/lastindexof[lastIndexOf()]
* #SPRACHE# link:../string/functions/length[length()]
* #SPRACHE# link:../string/functions/remove[remove()]
* #SPRACHE# link:../string/functions/replace[replace()]
* #SPRACHE# link:../string/functions/reserve[reserve()]
* #SPRACHE# link:../string/functions/setcharat[setCharAt()]
* #SPRACHE# link:../string/functions/startswith[startsWith()]
* #SPRACHE# link:../string/functions/substring[substring()]
* #SPRACHE# link:../string/functions/tochararray[toCharArray()]
* #SPRACHE# link:../string/functions/todouble[toDouble()]
* #SPRACHE# link:../string/functions/toint[toInt()]
* #SPRACHE# link:../string/functions/tofloat[toFloat()]
* #SPRACHE# link:../string/functions/tolowercase[toLowerCase()]
* #SPRACHE# link:../string/functions/touppercase[toUpperCase()]
* #SPRACHE# link:../string/functions/trim[trim()]

[float]
=== Operatoren

[role="language"]
* #SPRACHE# link:../string/operators/elementaccess[[\] (Elementzugriff)]
* #SPRACHE# link:../string/operators/concatenation[+ (Verkettung)]
* #SPRACHE# link:../string/operators/append[+= (Anhängen)]
* #SPRACHE# link:../string/operators/comparison[== (Vergleich)]
* #SPRACHE# link:../string/operators/greaterthan[> (Größer als)]
* #SPRACHE# link:../string/operators/greaterthanorequalto[>= (Größer als oder gleich)]
* #SPRACHE# link:../string/operators/lessthan[< (Kleiner als)]
* #SPRACHE# link:../string/operators/lessthanorequalto[\<= (Kleiner als oder gleich)]
* #SPRACHE# link:../string/operators/differentfrom[!= (Ungleich)]

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]


// SIEHE-AUCH-ABSCHNITT SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
