---
title: unsigned long
categories: [ "Variables" ]
subCategories: [ "Datentypen" ]
---

= unsigned long

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Long-Variablen ohne Vorzeichen sind Variablen mit erweiterter Größe für die Nummernspeicherung und speichern 32 Bit (4 Byte).
Im Gegensatz zu Standard-Longs werden bei unsigned Longs keine negativen Zahlen gespeichert, sodass der Bereich zwischen 0 und 4,294,967,295 (2^32 - 1) liegt.
[%hardbreaks]

[float]
=== Syntax

`unsigned long var = val;`

[float]
=== Parameter
`var`: Variablenname +
`val`: Der Wert, der der Variablen zugewiesen wird
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
unsigned long time;

void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.print("Time: ");
  time = millis();
  // Gibt die Zeit seit dem Programmstart aus
  Serial.println(time);
  // Wartet eine Sekunde, um keine riesigen Datenmengen zu senden
  delay(1000);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../constants/integerconstants[Ganzzahlkonstanten]

--
// SEE ALSO SECTION ENDS
