---
title: unsigned char
categories: [ "Variables" ]
subCategories: [ "Datentypen" ]
---

= unsigned char

// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Ein vorzeichenloser Datentyp belegt 1 Byte Speicher. Genauso wie der link:../byte[byte]-Datentyp.

Der vorzeichenlose char-Datentyp codiert Zahlen von 0 bis 255.

Für die Konsistenz des Arduino-Programmierstils ist der Byte-Datentyp zu bevorzugen.
[%hardbreaks]


[float]
=== Syntax
`unsigned char var = val`


[float]
=== Parameter
`var`: Variablenname. +
`val`: Der Wert, der der Variablen zugewiesen wird.

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
unsigned char myChar = 240;
----

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../../functions/communication/serial/println[Serial.println]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
