---
title: unsigned int
categories: [ "Variables" ]
subCategories: [ "Datentypen" ]
---

= unsigned int

// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Auf Uno und anderen ATMEGA-basierten Boards sind vorzeichenlose Ganzzahlen (`unsigned int`) die gleichen wie `int`, da sie einen 2-Byte-Wert speichern.
Anstatt negative Zahlen zu speichern, speichern sie jedoch nur positive Werte, was einen Bereich von 0 bis 65,535 (2^16 - 1) ergibt.

The Due stores a 4 byte (32-bit) value, ranging from 0 bis 4,294,967,295 (2^32 - 1).

Der Unterschied zwischen vorzeichenlosen `int` und `signed int` liegt in der Art und Weise, wie das höchste Bit, manchmal als "Vorzeichen" bezeichnet, interpretiert wird.
Wenn im Arduino `int`-Typ (der mit Vorzeichen versehen ist) das High-Bit eine "1" ist, wird die Zahl als negative Zahl interpretiert und die anderen 15 Bits werden interpretiert
mit dem (https://de.wikipedia.org/wiki/Zweierkomplement[Zweierkomplement]).
[%hardbreaks]

--
// ÜBERSICHTSABSCHNITT ENDET

[float]
=== Syntax
`unsigned int var = val`


[float]
=== Parameter
`var`: Variablenname. +
`val`: Der Wert, der der Variablen zugewiesen wird.
[%hardbreaks]

// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
unsigned int ledPin = 13;
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn Variablen ohne Vorzeichen ihre maximale Kapazität überschreiten, "rollen" sie wieder auf 0 zurück und umgekehrt:

[source,arduino]
----
unsigned int x;
x = 0;
x = x - 1; // x enthält jetzt 65535
x = x + 1; // x enthält jetzt 0
----


--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../constants/integerconstants[Ganzzahlkonstanten]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
