---
title: "=="
title_expanded: comparison
categories: [ "Data Types" ]
subCategories: [ "StringObject Operator" ]
---





= == Vergleich


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Vergleicht zwei Zeichenfolgen auf Gleichheit.
Bei dem Vergleich wird zwischen Groß- und Kleinschreibung unterschieden.
Dies bedeutet, dass der `String` "hallo" nicht mit dem `String` "HALLO" übereinstimmt. Funktioniert genauso wie `string.equals()`.


[%hardbreaks]


[float]
=== Syntax
`myString == myString2`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`myString2`: Eine weitere Variable vom Typ `String`. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
Das n-te Zeichen der Zeichenfolge. Gleich wie `charAt()`. +
`true`: Wenn `myString` gleich `myString2` ist. + 
`false`: Sonst.
--

// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
