---
title: "+"
title_expanded: concatenation
categories: [ "Data Types" ]
subCategories: [ "StringObject Operator" ]
---





= + Verkettung


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Kombiniert oder verkettet zwei Strings zu einem neuen `String`. Der zweite `String` wird an den ersten angehängt und das Ergebnis wird in einen neuen `String` eingefügt.
Funktioniert genauso wie `string.concat()`.

[%hardbreaks]


[float]
=== Syntax
`myString3 = myString + myString2`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`myString2`: Eine weitere Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`myString3`: Eine dritte Variable vom Typ `String`. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
Neuer `String`, der die Kombination der ursprünglichen zwei Strings darstellt.

--

// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
