---
title: ">="
title_expanded: Größer als oder gleich
categories: [ "Data Types" ]
subCategories: [ "StringObject Operator" ]
---





= >= Größer als oder gleich


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Prüft, ob der `String` links größer ist als der `String` rechts. Dieser Operator wertet Strings in alphabetischer Reihenfolge nach dem ersten Zeichen aus, bei dem sich die beiden unterscheiden.
Also zum Beispiel "b"> = "a" und "2"> = "1", aber "999"> = "1000", weil 9 nach 1 kommt.

Achtung: `String`-Vergleichsoperatoren können beim Vergleichen von numerischen Strings verwirrend sein, da die Zahlen als Strings und nicht als Zahlen behandelt werden.
Wenn du Zahlen numerisch vergleichen musst, vergleiche sie als `int`, `float` oder `long` und nicht als `String`.

[%hardbreaks]


[float]
=== Syntax
`myString >= myString2`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`myString2`: Eine weitere Variable vom Typ `String`. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
`true`: Wenn `myString` größer oder gleich `myString2` ist. +
`false`: Sonst.
--

// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SEE ALSO SECTION ENDS
