---
title: Mouse
categories: [ "Functions" ]
subCategories: [ "USB" ]

---





= Mouse


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Die `mouse`-Funktionen ermöglichen es, auf 32u4- oder SAMD-micro-basiertend Boards den Mauszeiger auf einem verbundenem Computer über dessen nativen USB-Port zu steuern.
Wenn man die Mauszeigerposition ändert, so ist die neue Position immer relativ zu der vorhergehenden Position.
[%hardbreaks]
--
// ÜBERSICHTSABSCHNITT ENDET


[float]
=== Anmerkungen und Warnungen
Diese Core-Bibliotheken erlauben es 32u4- oder SAMD-basierten Boards (Leonardo, Esplora, Zero, Due und MKR Family), als native Maus und/oder Tastatur auf dem verbundenen Computer zu erscheinen.
[%hardbreaks]
*Achtung: Wenn die Maus oder Tastatur permanent läuft, wird es schwer, das Board noch zu programmieren. Funktionen wie `Mouse.move()` und `Keyboard.print()` bewegen den Cursor oder senden Tastenanschläge
an den verbundenen Computer. Diese Funktionen sollten nur aufgerufen werden, wenn das Programm diese behandeln kann. Es wird deshalb empfohlen, ein Kontrollsystem zu nutzen, z.B. einen physikalischen Schalter
oder nur auf bestimmte Eingaben zu antworten.
[%hardbreaks]
Wenn die Mouse- oder Keyboard-Bibliothek benutzt wird, sollte die Ausgabe zunächst mit `_Serial_.print()` überprüft werden. Auf diesem Weg kann man sich sicher sein, dass die richtigen Werte an den verbundenen
Computer gesendet werden. Die Beispiele liefern weitere Informationen dazu.

// FUNCTIONS SECTION STARTS
[#functions]
--

'''

[float]
=== Funktionen
link:../mouse/mousebegin[Mouse.begin()] +
link:../mouse/mouseclick[Mouse.click()] +
link:../mouse/mouseend[Mouse.end()] +
link:../mouse/mousemove[Mouse.move()] +
link:../mouse/mousepress[Mouse.press()] +
link:../mouse/mouserelease[Mouse.release()] +
link:../mouse/mouseispressed[Mouse.isPressed()]

'''

--
// FUNCTIONS SECTION ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# http://www.arduino.cc/en/Tutorial/KeyboardAndMouseControl[KeyboardAndMouseControl^]: Zeigt, wie die Mouse- und Keyboard-Bibliothek verwendet werden.
* #BEISPIEL# http://www.arduino.cc/en/Tutorial/ButtonMouseControl[ButtonMouseControl^]: Steuert den Mauszeiger mit 5 Buttons.
* #BEISPIEL# http://www.arduino.cc/en/Tutorial/JoystickMouseControl[JoystickMouseControl^]: Steuert den Mauszeiger eines Computers mit einem Joystick, wenn ein Button gedrückt wird.

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET

