---
title: continue
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= continue


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
[%hardbreaks]
Das `continue`-Statement überspringt die restliche Iteration einer Schleife (`link:../for[for]`, `link:../while[while]` oder `link:../dowhile[do...while]`).
Das `continue`-Statement checkt anschließend die `condition` und durchläuft die Schleife erneut, bis die Abbruchbedingung erreicht ist.
[%hardbreaks]

[float]
=== Syntax
[source,arduino]
----
while (condition) {
   //Statement(s)
   continue;
   //Statement(s)
}
----

[float]
=== Parameter
Keine.

[float]
=== Rückgabewert
Nichts.
--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Der Code schreibt die Werte von 0 bis 255 auf den LED-Pin, aber überspringt Werte zwischen 41 und 119.

[source,arduino]
----
// Iteriere über die Werte von 0 bis 255
for (int x = 0; x <= 255; x ++) {
  // Springe bei den Werten zwischen 40 und 120 weiter
  if (x > 40 && x < 120){
    continue;
  }
  // Schreibe den Wert auf den LED-Pin
  analogWrite(PWMpin, x);
  // Warte 50 Millieskunden
  delay(50);
}
----


--
// HOW-TO-USE-ABSCHNITT ENDET



// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
