---
title: do...while
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= do...while loop


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
[%hardbreaks]
`do...while` funktioniert genauso wie eine `link:../while[while]`-Schleife. Der einzige Unterschied ist, dass `do...while` immer mindestens einmal ausgeführt wird,
da die Bedingung erst am Schluss der Schleife getestet wird.

[float]
=== Syntax
[source,arduino]
----
do {
   //Statement(s)
} while (condition);
----


[float]
=== Parameter
`condition`: Ein Ausdruck, der auf `link:../../../variables/constants/constants[true]` oder `link:../../../variables/constants/constants[false]` evaluiert.


[float]
=== Rückgabewert
Nichts.
--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Liest in do-while-Schleife 100 Mal einen Sensorwert aus.

[source,arduino]
----
// Initialisiere x und i mit Wert 0
int x = 0;
int i = 0;

do {
  delay(50);          // Warte 50 Millieskunden, bis der Sensor wieder einen stabilen Wert liefert.
  x = readSensor();   // Lies den Sensorwert
  i++;
} while (i < 100);    // Wiederhole den Vorgang 100 Mal
----


--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
