---
title: else
categories: [ "Structure" ]
subCategories: [ "Kontrollstruktur" ]
---





= if...else


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`if...else` erlaubt mehr Optionen als das einfache link:../if[if]. Es erlaubt, mehrere Variablen hintereinander abzufragen. Der `else`-Teil wird dann ausgeführt,
wenn die Bedingung im `if`-Teil `false` ist. Auf den `else`-Teil kann wieder ein `if` folgen, sodass viele sich gegenseitig ausschließende Konditionen gestestet werden können.
[%hardbreaks]

Dabei wird immer weiter fortgefahren, bis ein Test auf `true` evaluiert wird. Daraufhin wird dessen zugehöriger Code ausgeführt, woraufhin das Programm ans Ende des kompletten
`if...else`-Konstrukts springt. Wenn ein Default-`else`-Teil vorhanden ist, wird dieser ausgeführt, wenn alle anderen Tests auf `false` evaluiert wurden.
[%hardbreaks]

Ein `else if`-Block kann benutzt werden ohne einen terminierenden `else`-Block und umgekehrt. Somit ist eine unbegrenzte Anzahl an `else if`s möglich.

[float]
=== Syntax
[source,arduino]
----
if (condition1) {
  // Tue Task 1
}
else if (condition2) {
  // Tue Task 2
}
else {
  // Tue Task 3
}
----


[float]
=== Parameter
`condition`: Die Bedingung, die abgeprüft wird. Evaluiert zu `true` oder `false`.


[float]
=== Rückgabewert
Nichts.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Der folgende Code testet einige Werte in den Bedingungen ab. Im Detail handelt es sich um ein simples Temperaturwarnsystem.

[source,arduino]
----
if (temperature >= 70) {
  //Schalte das System ab
}
else if (temperature >= 60 && temperature < 70) {
  //Schicke dem Benutzer eine Warnung
}
else {
  //Keine Probleme erkannt.
}
----

--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
