---
title: for
categories: [ "Structure" ]
subCategories: [ "Kontrollstruktur" ]
---





= for loop


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Das `for`-Statement wiederholt die in Klammern nachfolgenden Anweisungen. Meistens wird eine Zählervariable verwendet, welche hochgezählt wird und die Schleife irgendwann beendet.
Das `for`-Statement wird häufig zur Iteration über Arrays oder Listen von Daten oder Pins verwendet.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
for (initialization; condition; increment) {
	// Statement(s);
}
----

[float]
=== Parameter
`initialization`: Passiert genau einmal am Anfang der Schleife. +
`condition`: Wird bei jedem Schleifendurchlauf getestet. Wenn sie `link:../../../variables/constants/constants[true]` ist, werden alle Statements in den Klammern ausgeführt und `increment` hochgezählt. Wenn
			 die `condition` `link:../../../variables/constants/constants[false]` ist, wird die Schleife abgebrochen. +
`increment`: Wird hochgezählt, wenn die `condition` link:../../../variables/constants/constants[`true`] ist.


[float]
=== Rückgabewert
Nichts.

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Eine LED wird über einen PWM-Pin gedimmt.

[source,arduino]
----
int PWMpin = 10; // LED in Serie mit 470-Ohm-Widerstand auf Pin 10

void setup() {
  // Nichts
}

void loop() {
  // Wiederhole 255 Mal:
  for (int i=0; i <= 255; i++){
    // Schreibe den Wert von "i" auf den LED-Pin
    analogWrite(PWMpin, i);
    // Warte 10 Millisekunden
    delay(10);
  }
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Die `for`-Schleife in pass:[C++] ist deutlich ausgeprägter als in anderen Sprachen wie z.B. BASIC. Einige oder sogar alle der 3 Parameter können weggelassen werden,
allerdings sind die Strichpunkte immer nötig. Alle 3 Parameter können mit beliebigen Variablen belegt werden und jeden Datentyp inklusive `float` nutzen.
Die Beispiele unten zeigen die Verwendung einiger Spezialformen der `for`-Schleife.
[%hardbreaks]

Eine Multiplikation im `increment` generiert ein logarithmisches Verhalten:

[source,arduino]
----
for(int x = 2; x < 100; x = x * 1.5) {
   println(x);
}
----

Gibt aus: 2,3,4,6,9,13,19,28,42,63,94
[%hardbreaks]

LED hoch- und runterdimmen in einer Schleife:

[source,arduino]
----
void loop() {
  // Globale Zählervariable "x"
  int x = 1;
  // Laufe über die Variable solange i größer -1 ist und zähle i um x hoch
  for (int i = 0; i > -1; i = i + x){
    // Schreibe auf den LED-Pin
    analogWrite(PWMpin, i);
    if (i == 255) {
	  x = -1; // Ändere die Richtung des Dimmens auf dem "Peek"
      // Warte 10 Millisekunden
      delay(10);
	}
  }
}
----


--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
