---
title: goto
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= goto


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Springt im Programmfluss zu einem bestimmten benannten Punkt.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
label:

goto label; // Springt zu dem Label.
----

[float]
=== Parameter
`label`: Das Label an der Stelle, zu der gesprungen werden soll.

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

Der Code zeigt, wie `goto` aus einem Programm mit 3 Schleifen an eine bestimmte Stelle springt.

[source,arduino]
----
for(byte r = 0; r < 255; r++){
    for(byte g = 255; g > -1; g--){
        for(byte b = 0; b < 255; b++){
            if (analogRead(0) > 250){ goto bailout;}
            // Weitere Statements
        }
    }
}

bailout:
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Es wird nicht empfohlen, `goto` in der C++-Programmierung zu verwenden. Viele Autoren sagen sogar, dass der `goto`-Operator unnötig ist.
Das Problem mit `goto` ist, dass der Code schnell nahezu unlesbar wird und nicht mehr zu debuggen ist.

Manchmal kann ein `goto` nützlich sein. Z.B um aus einer hohen Schleifentiefe wie im Beispielcode oben herauszuspringen (Obwohl dies mit link:../return[return] auch klappen würde).
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch
[role="language"]

--
// SEE ALSO SECTION ENDS
