---
title: return
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= return


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Beendet eine Funktion und gibt einen Wert an die aufrufende Funktion zurück, wenn gewünscht.
[%hardbreaks]


[float]
=== Syntax
`return` +
`return value; // Beide Formen davon sind gültig`


[float]
=== Parameter
`value`: Beliebige Variable oder Parameter. Erlaubte Datentypen: Beliebiger Datentyp.


[float]
=== Rückgabewert
Den Datentyp des Parameters `value`.

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄

Vergleicht einen Sensorwert mit einem Thresholdwert.

[source,arduino]
----
int checkSensor() {
  // Lies Wer von Sensor ein und vergleiche diesen mit der Konstante 400
  if (analogRead(0) > 400) {
    // Wenn Sensorwert größer als 400: Gib 1 zurück
    return 1;
  }
  else {
    // Sonst gib 0 zurück
    return 0;
  }
}
----

Das `return`-Keywort kann dazu dienen, Codeabschnitte zu testen ohne viel Code auskommentieren zu müssen.


[source,arduino]
----
void loop() {
  // Codeidee, die getestet werden soll, hier.

  return;

  // Der Rest des Sketches hier.
  // Wird niemals ausgeführt
}
----
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET





// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch
[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
