---
title: switch...case
categories: [ "Structure" ]
subCategories: [ "Kontrollstruktur" ]
---





= switch...case statement


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Wie auch link:../if[if]-Statements, erlaubt es auch `switch case`, dass abhängig von der Bedingung in verschiedenen Situationen unterschiedlicher Code ausgeführt wird.
Im Detail vergleicht `switch case` die Variablenwerte mit denen in den `case`-Statements. Wenn ein passendes `case`-Statement gefunden wird, so wird der Code in diesem
`case`-Statement ausgeführt.
[%hardbreaks]

Das link:../break[break]-Keywort beendet das `switch case`-Statement und wird üblicherweise am Ende jedes `case`-Statements verwendet. Wenn kein link:../break[break]-Keywort
verwendet wird, führt `switch case` alle Statements aus, bis ein link:../break[break]-Keywort auftaucht oder das `switch case` zu Ende ist.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
switch (var) {
  case label1:
    // Statement(s)
    break;
  case label2:
    // Statement(s)
    break;
  default:
    // Statement(s)
    break; // Wird nicht benötigt, wenn Statement(s) vorhanden sind
}
----


[float]
=== Parameter
`var`: Eine Variable, die mit den eizelnen Fällen verglichen werden sollen *Erlaubte Datentypen:* int, char +
`label1`, `label2`: Konstanten. *Erlaubte Datentypen:* int, char

[float]
=== Rückgabewert
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Das Code-Beispiel zeigt die Verwendung des switch-case-Statements.

[source,arduino]
----
switch (var) {
  case 1:
    // Tue etwas, wenn "var" 1 ist
    break;
  case 2:
    // Tue etwas, wenn "var" 2 ist
    break;
  default:
    // Tue etwas, im Defaultfall
    // Dieser Fall ist optional
    break; // Wird nicht benötigt, wenn Statement(s) vorhanden sind
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTIN BEGINS
[#see_also]
--

[float]
=== Siehe auch
[role="language"]

--
// SEE ALSO SECTION ENDS
