---
title: while
categories: [ "Structure" ]
subCategories: [ "Kontrollstruktur" ]
---





= while loop


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
[%hardbreaks]
Eine `while`-Schleife läuft solange weiter (Eventuell auch unendlich), bis die Bedingung in den Klammern `()` `false` wird. Wenn die Variable in der Schleife
sich nie ändert, läuft die Schleife unendlich. Dies kann z.B. durch das Hochzählen einer Variable oder das Lesen eines Sensorwertes erfolgen.

[float]
=== Syntax
[source,arduino]
----
while(condition) {
  // Statement(s)
}
----


[float]
=== Parameter
`condition`: Ein Ausdruck, der auf `true` oder `false` evaluiert.


[float]
=== Rückgabewert
Nichts.

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Dieser Code zählt eine Variable 200-mal um 1 hoch.

[source,arduino]
----
var = 0;
// Wiederhole etwas 200 Mal
while(var < 200) {
  // Zähle Variable x um 1 hoch
  var++;
}
----

--
// HOW-TO-USE-ABSCHNITT ENDET



// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

[role="example"]
* #BEISPIEL#	https://arduino.cc/en/Tutorial/WhileLoop[While^]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
