---
title: analogRead()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---




= analogRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Liest den Wert vom angegebenen analogen Pin ein. Das Arduino-Board enthält einen 6-Kanal- (8-Kanal- auf dem Mini und Nano, 16-Kanal- auf dem Mega) 10-Bit-Digital-Konverter. D.h. das Board mappt Eingangsspannungen zwischen 0 und 5 V auf Integer-Werte zwischen 0 und 1023. Die erreichte Auflösung ist damit 5 V / 1024 Teile oder 0,0049 V (4,9 mV) per Teil. Die Eingangsspannung und Auflösung kann mit link:../analogreference[analogReference()] geändert werden.

Um einen analogen Pin zu lesen, benötigt das Board circa 100 Mikrosekunden (0,0001 s). Damit ist die maximale Lesegeschwindigkeit 10000 Lesevorgänge pro Sekunde.
[%hardbreaks]


[float]
=== Syntax

`analogRead(pin)`

[float]
=== Parameter
`pin`: Die Pinnummer, von der gelesen werden soll (0 bis 5 auf den meisten Boards, 0 bis 7 auf dem Mini und Nano, 0 bis 15 auf dem Mega)

[float]
=== Gibt zurück
int(0 to 1023)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code liest die Spannung auf einem Analogpin und zeigt diese an.

[source,arduino]
----
int analogPin = 3;     // Pin, der gelesen werden soll: Pin 3
int val = 0;           // Variable, die den gelesenen Wert speichert

void setup()
{
  Serial.begin(9600);              //  Setup der seriellen Verbindung
}

void loop()
{
  val = analogRead(analogPin);     // Pin einlesen
  Serial.println(val);             // Wert ausgeben
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn der analoge Pin nicht verbunden ist, wird der zurückgegebene Wert schwanken basierend auf mehreren Faktoren (z.B. Die Werte der anderen analogen Pins, Wie nahe die Hand am Board ist, etc.).

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()]
* #LANGUAGE# https://www.arduino.cc/en/Tutorial/AnalogInputPins[Tutorial: Analoge Eingangspins]
--
// SEE ALSO SECTION ENDS
