---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Konfiguriert die Referenzspannung, die für analoge Eingabe-Pins genutzt wird (z.B. Der maximal Wert der Eingangsspannung). Dabei sind die folgenden Optionen verfügbar:

* DEFAULT: Default analoge Einstellung (5 V für 5 V-Arduino; 3,3 V für 3,3 V-Arduinos)
* INTERNAL: Eingebaute Referenz; Festgelegt auf 1,1 V auf dem ATmega168 oder ATmega328P und 2,56 V auf dem ATmega8 (Nicht verfügbar auf dem Arduino Mega) 
* INTERNAL1V1: Eingebaute Referenz; 1,1 V (Nur Arduino Mega)
* INTERNAL2V56: Eingebaute Referenz; 2,56 V (Nur Arduino Mega)
* EXTERNAL: Die Spannung, die auf dem AREF-Pin (nur 0 bis 5 V) angelegt ist, wird als Referenz verwendet.
[%hardbreaks]


[float]
=== Syntax
`analogReference(type)`


[float]
=== Parameter
`type`: Welche Art von Einstellung benutzt werden soll (DEFAULT, INTERNAL, INTERNAL1V1, INTERNAL2V56, oder EXTERNAL).

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Wenn die Referenzspannung geändert wird, können die ersten Messwerte von `analogRead()` fehlerhaft sein.

* Benutze niemals Spannungen geringer als 0 V oder höher als 5 V für externe Referenzspannungen auf dem AREF-Pin! Wenn du eine externe Referenzspannung auf dem AREF-Pin nutzen willst, musst du zunächst die analoge Referenzspannung auf EXTERNAL setzen, bevor du `analogRead()` nutzen kannst.
* Sonst kann es dazu führen, dass auf dem Board ein Kurzschluss entsteht zwischen interner und auf dem AREF-Pin angelegter Spannung. Dies kann eine Beschädigung des Mikrokontrollers oder Boards zur Folge haben.

Alternativ kannst du die externe Referenzspannung auf dem AREF-Pin über einen 5k-Widerstand verbinden. Das hat den Vorteil, dass du zwischen externer und interner Referenzspannung wechseln kannst. Beachte auch, dass sich dadurch die Nutzungsspannung ändert, weil der AREF-Pin einen internen 32K-Widerstand besitzt. Diese 2 Widerstände funktionieren als Spannungsteiler. Wenn also 2,5 V durch den Widerstand fließen, werden auf dem AREF-Pin 2.5 * 32 / (32 + 5) V = ~2.2 V anliegen.

[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Beschreibung der analogen Eingangspins]

--
// SEE ALSO SECTION ENDS
