---
title: analogWrite()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---





= analogWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Schreibt einen Analogwert (http://arduino.cc/en/Tutorial/PWM[PWM-Welle]) auf einen Pin. Kann z.B. benutzt werden, um eine LED mit verschiedener Helligkeit leuchten zu lassen oder einen Motor mit unterschiedlicher Geschwindigkeit laufen zu lassen. Nach Aufruf von `analogWrite()` generiert die Funktion eine stetige Rechteckwelle mit angegebenem Zyklus, bis der nächste Aufruf von `analogWrite()` (oder `digitalRead()` oder `digitalWrite()`) auf dem gleichen Pin erfolgt. Die Frequenz des PWM-Signals beträgt auf den meisten Pins circa 490 Hz. Auf dem Uno und ähnlichen Boards liegt die Frequenz auf Pin 5 und 6 bei circa 980 Hz.
[%hardbreaks]
Auf den meisten Arduino-Boards (Die Boards mit dem ATmega168 oder ATmega328P) funktioniert diese Funktion auf den Pins 3, 5, 6, 9, 10, und 11. Auf dem Arduino Mega funktioniert die Funktion auf den Pins 2 bis 13 und 44 bis 46. Ältere Arduino-Boards mit dem ATmega8 unterstützen `analogWrite()` nur auf den Pins 9, 10, und 11. Der Arduino DUE unterstützt `analogWrite()` auf den Pins 2 bis 13 sowie zusätztlich auf den Pins DAC0 und DAC1. DAC0 und DAC1 sind Digital-zu-analog-Konverter und arbeiten als *wahre* analoge Ausgänge. Du musst keinen Pin explizit als Ausgabepin über `pinMode()` festlegen, bevor du `analogWrite()` nutzt. Die `analogWrite`-Funktion hat nichts mit analogen Pins oder der `analogRead`-Funktion.
[%hardbreaks]


[float]
=== Syntax
`analogWrite(pin, value)`


[float]
=== Parameter
`pin`: Der Pin auf den geschrieben werden soll (int)

`value`: Die Zykluszeit. Werte zwischen 0 (immer aus) und 255 (immer an) (int)

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
Setzt die Ausgabe auf dem LED-Pin proportional zu dem Wert, der von einem Potentiometer gelesen wird.

[source,arduino]
----
int ledPin = 9; // LED auf Digitalpin 9 verbunden
int analogPin = 3; // Potentiometer auf Pin 3 verbunden
int val = 0; // Variable, um den gelesenen Wert zu speichern

void setup() {
  pinMode(ledPin, OUTPUT); // Setzt den Pin als output.
}

void loop() {
  val = analogRead(analogPin); // Liest den Wert vom Pin ein
  analogWrite(ledPin, val / 4); // analogRead: Werte von 0 bis 1023, analogWrite: Werte von 0 bis 255
}
----
[%hardbreaks]


[float]
=== Anmerkungen und Warnungen
Die PWM-Ausgaben auf Pins 5 und 6 werden höhere Zyklen als erwartet haben. Dies passiert, weil die Funktionen `millis()` und `delay()` den gleichen internent Timer nutzen, um diese PWM-Ausgaben zu generieren. In kleinen Zyklen (z.B. 0 bis 10) ist der Effekt am stärksten und kann dazu führen, dass der Wert 0 die Spannung auf Pin 5 und 6 nicht komplett wegnimmt, d.h. dass z.B. bei Wert 0 die LED trotzdem leuchtet.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #DEFINITION# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Blink[Blinken^]

--
// SEE ALSO SECTION ENDS
