---
title: constrain()
categories: [ "Functions" ]
subCategories: [ "Mathematik" ]
---





= constrain(x, a, b)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Beschränkt eine Zahl auf einen Bereich.
[%hardbreaks]


[float]
=== Syntax
`constrain(x, a, b)`


[float]
=== Parameter
`x`: Die zu beschränkende Zahl. Erlaubte Datentypen: Beliebiger Datentyp. +
`a`: Das unteren Ende des Bereichs. Erlaubte Datentypen: Beliebiger Datentyp. +
`b`: Das obere Ende des Bereichs. Erlaubte Datentypen: Beliebiger Datentyp.


[float]
=== Rückgabewert
x: Wenn x zwischen a und b liegt. +
a: Wenn x kleiner als a ist. +
b: Wenn x größer als b ist.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code begrenzt den Bereich der Sensorwerte auf 10 bis 150.

[source,arduino]
----
sensVal = constrain(sensVal, 10, 150);    // Begrenzt den Bereich der Sensorwerte auf 10 bis 150.
----

[float]
=== Anmerkungen und Warnungen
Es sollten keine anderen Funktionen innerhalb der Klammern verwendet werden. Dies kann zu falschen Ergebnissen führen.

Dieser Code führt zu falschen Ergebnissen:
[source,arduino]
----
int constrainedInput = constrain(Serial.parseInt(), minimumValue, maximumValue); // Vermeide dies
----

Benutze stattdessen diesen Code:
[source,arduino]
----
int input = Serial.parseInt(); // Halte andere Operationen außerhalb der Einschränkungsfunktion
int constrainedInput = constrain(input, minimumValue, maximumValue);
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
