---
title: max()
categories: [ "Functions" ]
subCategories: [ "Mathematik" ]
---





= max(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Berechnet das Maximum von zwei Zahlen.
[%hardbreaks]


[float]
=== Syntax
`max(x, y)`


[float]
=== Parameter
`x`: Die erste Zahl, beliebiger Datentyp

`y`: Die zweite Zahl, beliebiger Datentyp

[float]
=== Rückgabewert
Der größere der beiden Parameterwerte.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code stellt sicher, dass sensVal mindestens 20 beträgt.

[source,arduino]
----
sensVal = max(senVal, 20); // Ordnet sensVal dem größeren Wert von sensVal oder 20 zu
                           // (Stellt sicher, dass sensVal mindestens 20 ist)
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Vielleicht kontra-intuitiv wird `max()` häufig verwendet, um das untere Ende des Bereichs einer Variablen zu beschränken, während `min()` verwendet wird, um das obere Ende des Bereichs zu beschränken.

Es sollten keine anderen Funktionen innerhalb der Klammern verwendet werden. Dies kann zu falschen Ergebnissen führen.
[source,arduino]
----
max(a--, 0); // Vermeide dies - führt zu falschen Ergebnissen

max(a, 0); // Benutze dies stattdessen -
a--;       // Andere Mathematik außerhalb der Funktion halten
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
