---
title: min()
categories: [ "Functions" ]
subCategories: [ "Mathematik" ]
---





= min(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Berechnet das Minimum von zwei Zahlen.
[%hardbreaks]


[float]
=== Syntax
`min(x, y)`


[float]
=== Parameter
`x`: Die erste Zahl, beliebiger Datentyp

`y`: Die zweite Zahl, beliebiger Datentyp

[float]
=== Gibt zurück
Die kleinere der beiden Zahlen.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Besipielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code stellt sicher, dass der Wert niemals über 100 hinausgeht.

[source,arduino]
----
sensVal = min(sensVal, 100); // Ordnet sensVal dem kleineren Wert von sensVal oder 100 zu.
                             // Sorgt dafür, dass sensVal nie über 100 kommt.
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Vielleicht kontra-intuitiv wird `max()` häufig verwendet, um das untere Ende des Bereichs einer Variablen zu beschränken, während `min()` verwendet wird, um das obere Ende des Bereichs zu beschränken.

Es sollten keine anderen Funktionen innerhalb der Klammern verwendet werden. Dies kann zu falschen Ergebnissen führen.
[source,arduino]
----
min(a++, 100); // Vermeide dies - führt zu falschen Ergebnissen

min(a, 100); // Benutze dies stattdessen -
a++;         // Andere Mathematik außerhalb der Funktion halten
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
