---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Mathematik" ]
---

= pow(base, exponent)

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Berechnet den Wert einer Zahl, die auf eine Potenz erhöht wird. Mit `pow ()` kann eine Zahl auf eine gebrochene Potenz erhöht werden.
Dies ist nützlich, um eine exponentielle Abbildung von Werten oder Kurven zu erstellen.
[%hardbreaks]


[float]
=== Syntax
`pow(base, exponent)`


[float]
=== Parameter
`base`: Die Zahl (`float`)

`exponent`: Die Potenz, auf die die Zahl angehoben wird (`float`)

[float]
=== Rückgabewert
Das Ergebnis der Potenzierung. (`double`)

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Berechnet den Wert von x mit Potenz von y:
[source,arduino]
----
z = pow(x, y);
----
Siehe auch den (http://arduino.cc/playground/Main/Fscale[fscale]) Sketch für ein komplexeres Beispiel der `pow()`-Funktion.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="definition"]
* #DEFINITION# link:../../../variables/data-types/float[float]
* #DEFENITION# link:../../../variables/data-types/double[double]

--
// SEE ALSO SECTION ENDS
