---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Mathematik" ]
---





= pow(base, exponent)

// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Berechnet den Wert einer Zahl, die auf eine Potenz erhöht wird. Mit `pow()` kann eine Zahl auf eine gebrochene Potenz erhöht werden.
Dies ist nützlich, um eine exponentielle Abbildung von Werten oder Kurven zu erstellen.
[%hardbreaks]


[float]
=== Syntax
`pow(base, exponent)`


[float]
=== Parameter
`base`: Die Zahl. Erlaubte Datentypen: `float`. +
`exponent`: Die Potenz, auf die die Zahl angehoben wird. Erlaubte Datentypen: `float`.


[float]
=== Rückgabewert
Das Ergebnis der Potenzierung. Erlaubte Datentypen: `double`.

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Berechnet den Wert von x mit Potenz von y:
[source,arduino]
----
z = pow(x, y);
----
Siehe auch den (http://arduino.cc/playground/Main/Fscale[fscale]) Sketch für ein komplexeres Beispiel der `pow()`-Funktion.
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="definition"]
* #DEFINITION# link:../../../variables/data-types/float[float]
* #DEFENITION# link:../../../variables/data-types/double[double]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
