---
title: const
categories: [ "Variables" ]
subCategories: [ "Variablenscope und Bezeichner" ]
---





= const keyword


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Das `const`-Keywort steht für Konstanten. Es ist ein Variablenkennzeichner, der das Verhalten der Variable verändert. In diesem Fall wird die Variable "_read-only_".
Das bedeutet, dass die Variable wie alle anderen Variablen des gleichen Typs benutzt werden kann, aber dass der Wert unveränderlich ist. Wenn du der Variable einen
neuen Wert zuweist, bekommst du einen Compiler-Fehler.

Konstanten, die mit `const` versehen sind, folgen den Regeln des link:../scope[Variablenscopes]. Dieses Vorgehen und die Fallen bei der Verwendung von
link:../../../structure/further-syntax/define[`#define`] sorgt dafür, dass `const` bevorzugt vor link:../../../structure/further-syntax/define[`#define`]
benutzt werden sollte.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Der Code zeigt die Verwendung von konstanten Variablen

[source,arduino]
----
// Definiere Pi als Konstante
const float pi = 3.14;
// Variable x zum Speichern des Ergebnisses
float x;

// ....

x = pi * 2; // Das ist erlaubt.
pi = 7;     // Illegal-Konstante darf/kann nicht verändert werden.
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
*`#define` oder `const`*

Du kannst entweder `const` oder link:../../../structure/further-syntax/define[`#define`] für Konstanten verwenden. Für link:../../data-types/array[arrays]
musst du `const` verwenden. Generell wird `const` vor link:../../../structure/further-syntax/define[`#define`] vorgezogen.


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../../structure/further-syntax/define[#define]

--
// SEE ALSO SECTION ENDS
