---
title: "isAlphaNumeric()"
categories: [ "Functions" ]
subCategories: [ "Zeichen" ]
---





= isAlphaNumeric(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Analysiert, ob ein Zeichen alphanumerisch ist. (Buchstabe oder Zahl). Gibt ``true`` zurück, wenn das Zeichen eine Zahl oder ein Buchstabe ist. 
[%hardbreaks]


[float]
=== Syntax
[source,arduino]

`isAlphaNumeric(thisChar)`


[float]
=== Parameter
`thisChar`: Variable. *Erlaubte Datentypen:* char

[float]
=== Rückgabewert
`true`: Wenn das Zeichen alphanumerisch ist.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
if (isAlphaNumeric(thisChar)) { // Testet, ob das Zeichen alphanumerisch ist.
	Serial.println("Das Zeichen ist alphanumerisch");
}
else {
	Serial.println("Das Zeichen ist nicht alphanumerisch");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#  link:../../../variables/data-types/char[char]
* #SPRACHE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #SPRACHE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #SPRACHE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
