---
title: "isPrintable()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isPrintable(thisChar)


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Analysiert, ob das Zeichen druckbar ist (Also jedes Zeichen, das eine Ausgabe erzeugt, auch das Leerzeichen). Gibt `true` zurück, wenn das Zeichen druckbar ist.
[%hardbreaks]


[float]
=== Syntax
`isPrintable(thisChar)`


[float]
=== Parameter
`thisChar`: Variable. Erlaubte Datentypen: `char`.


[float]
=== Rückgabewert
`true`: Wenn das Zeichen druckbar ist.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
if (isPrintable(thisChar)) { // Testet, ob das Zeichen druckbar ist.
	Serial.println("Das Zeichen ist druckbar.");
}
else {
	Serial.println("Das Zeichen ist nicht druckbar.");
}

----

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#  link:../../../variables/data-types/char[char]
* #SPRACHE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #SPRACHE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #SPRACHE# link:../../communication/serial/read[read()]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
