---
title: "isSpace()"
categories: [ "Functions" ]
subCategories: [ "Zeichen" ]
---





= isSpace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Analysiert, ob ein Zeichen ein Leerzeichen, formfeed (`'\f'`), newline (`'\n'`), carriage return (`'\r'`), horizontal tab (`'\t'`) oder vertical tab (`'\v'`)) ist. Gibt `true` zurück, wenn das Zeichen ein Leerzeichen ist.
[%hardbreaks]


[float]
=== Syntax
`isSpace(thisChar)`


[float]
=== Parameter
`thisChar`: Variable. Erlaubte Datentypen: `char`.


[float]
=== Rückgabewert
`true`: wenn das Zeichen ein Leerzeichen, formfeed (`'\f'`), newline (`'\n'`), carriage return (`'\r'`), horizontal tab (`'\t'`) oder vertical tab (`'\v'`)) ist.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
if (isSpace(thisChar)) { // Testet, ob das Zeichen eines der Leerzeichen ist.
	Serial.println("Das Zeichen ist keines der Leerzeichen");
}
else {
	Serial.println("Das Zeichen ist eines der Leerzeichen");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#  link:../../../variables/data-types/char[char]
* #SPRACHE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #SPRACHE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #SPRACHE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
