---
title: "isWhitespace()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isWhitespace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Analysiert, ob ein Zeichen ein Leerzeichen, formfeed ('\f'), newline ('\n'), carriage return ('\r'), horizontal tab ('\t') oder vertical tab ('\v')) ist. Gibt ``true`` zurück, wenn das Zeichen ein Leerzeichen ist.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
`isWhitespace(thisChar)`
----

[float]
=== Parameter
`thisChar`: Variable. *Erlaubte Datentypen:* char

[float]
=== Gibt zurück
`true`: Wenn das Zeichen ein Leerzeichen ist.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
if (isWhitespace(thisChar)) { // Testet, ob das Zeichen ein Leerzeichen ist.
	Serial.println("Das Zeichen ist ein Leerzeichen");
}
else {
	Serial.println("Das Zeichen ist kein Leerzeichen");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
