---
title: "isWhitespace()"
categories: [ "Functions" ]
subCategories: [ "Zeichen" ]
---





= isWhitespace(thisChar)


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Analysiert das Zeichen, ob es ein Leerzeichen oder ein Tab (`'\t'`) ist. Gibt `true` zurück, wenn das Zeichen ein Leerzeichen oder ein Tab (`'\t'`) ist.
[%hardbreaks]


[float]
=== Syntax
`isWhitespace(thisChar)`


[float]
=== Parameter
`thisChar`: Variable. Erlaubte Datentypen: `char`.


[float]
=== Rückgabewert
`true`: Wenn das Zeichen ein Leerzeichen oder ein Tab (`'\t'`) ist.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
if (isWhitespace(thisChar)) { // Testet, ob das Zeichen ein Leerzeichen oder ein Tab (`'\t'`) ist.
	Serial.println("Das Zeichen ist ein Leerzeichen oder ein Tab");
}
else {
	Serial.println("Das Zeichen ist kein Leerzeichen oder Tab");
}

----

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#  link:../../../variables/data-types/char[char]
* #SPRACHE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #SPRACHE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #SPRACHE# link:../../communication/serial/read[read()]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
