---
title: "&"
title_expanded: Referenzoperator
categories: [ "Structure" ]
subCategories: [ "Zeiger-Operatoren" ]
---





= & Referenzoperator


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Referenzierung ist eines der Features, bei denen Zeiger benötigt werden. Der Operator `&` wird dafür verwendet.
Wenn `x` eine Variable ist, dann ist `&x` die Adresse der Variable `x`.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code zeigt ein kleines Rechenbeispiel zur Verwendung von Zeigern.

[source,arduino]
----
int *p;       // Definiere einen Zeiger als Integerdatentyp
int i = 5;
int result = 0; // Initialisiere 'i' mit 5 und 'result' mit 0
p = &i;       // 'p' enthält nun die Adress von 'i'
result = *p;  // 'result' erhält nun den Wert, der an der Adress von 'i' steht
              // 'result' ist also 5
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Zeiger sind eines der komplexesten Themen für Anfänger beim Lernen von C. Es ist aber möglich, den Großteil der Arduino-Sketches ohne eine
einzige Verwendung von Zeigern zu schreiben. Zur Verwendung einiger Datenstrukturen sind Pointer aber unersätzlich und bieten eine starke
Vereinfachung des Codes an.
[%hardbreaks]


--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

[role="definition"]
* #DEFINITION#  https://en.wikipedia.org/wiki/Pointer_%28computer_programming%29[Pointers^]

--
// SEE ALSO SECTION ENDS
