---
title: loop()
categories: [ "Functions" ]
subCategories: [ "Sketch" ]
---





= loop()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
After creating a link:../setup[setup()] function, which initializes and sets the initial values, the `loop()` function does precisely what its name suggests, and loops consecutively, allowing your program to change and respond. Use it to actively control the Arduino board.
[%hardbreaks]

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Der Code zeigt ein kleines Beispiel, welches den einen Inputpin festlegt. Bei jedem Durchlauf wird je nach Zustand einen Wert
auf den seriellen Ausgang geschrieben. Anschließend wartet das Board eine Sekunde und beginnt den Durchlauf von Neuem.

[source,arduino]
----
// Lege Button auf Pin 3
int buttonPin = 3;

void setup() {
  // Starte die serielle Verbindung
  Serial.begin(9600);
  // Setze den Pin 3 als Inputpin
  pinMode(buttonPin, INPUT);
}

// Loop checkt den Button bei jedem Durchlauf und schreibt je nach Zustand einen Wert auf den seriellen Ausgang.
void loop() {
  // Wenn Pin HIGH ist, schreibe H
  if (digitalRead(buttonPin) == HIGH) {
    serialWrite('H');
  }
  // Sonst, schreibe L
  else {
    serialWrite('L');
  }
  //Warte 1 Sekunde
  delay(1000);
}
----

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
