---
title: loop()
categories: [ "Functions" ]
subCategories: [ "Sketch" ]
---





= loop()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Während in der `link:../setup[setup()]` Funktion Variablen, Pins und Bibliotheken einmalig initialisiert werden, macht die `loop()` Funktion genau das was ihr Name vermuten lässt. Sie ist eine Endlosschleife die nach jedem Durchlauf erneut aufgerufen wird. Dadurch kann dein Programm Variablen verändern, Daten lesen oder darauf reagieren.
Hier steuerst du was dein Board machen soll.
[%hardbreaks]

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Der Code zeigt ein kleines Beispiel, welches den einen Inputpin festlegt. Bei jedem Durchlauf wird je nach Zustand einen Wert
auf den seriellen Ausgang geschrieben. Anschließend wartet das Board eine Sekunde und beginnt den Durchlauf von Neuem.

[source,arduino]
----
// Lege Button auf Pin 3
int buttonPin = 3;

void setup() {
  // Starte die serielle Verbindung
  Serial.begin(9600);
  // Setze den Pin 3 als Inputpin
  pinMode(buttonPin, INPUT);
}

// Loop checkt den Button bei jedem Durchlauf und schreibt je nach Zustand einen Wert auf den seriellen Ausgang.
void loop() {
  // Wenn Pin HIGH ist, schreibe H
  if (digitalRead(buttonPin) == HIGH) {
    serialWrite('H');
  }
  // Sonst, schreibe L
  else {
    serialWrite('L');
  }
  //Warte 1 Sekunde
  delay(1000);
}
----

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
