---
title: "%="
title_expanded: Zusammengesetzter Rest
categories: [ "Structure" ]
subCategories: [ "Verbundoperatoren" ]
---





= %= Zusammengesetzter Rest


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Dies ist eine praktische Abkürzung, um den Rest zu berechnen, wenn eine ganze Zahl durch eine andere geteilt wird.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
x %= divisor; // Äquivalent zum Ausdruck x = x% divisor;
----

[float]
=== Parameter
`x`: Variable. *Erlaubte Datentypen:* int +
`divisor`: *nicht null* Variable oder Konstante. *Erlaubte Datentypen:* int

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int x = 7;
x %= 5; // x enthält jetzt 2
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
1. Der zusammengsetzte Rest-Operator funktioniert nicht mit floats.

2. Wenn der *erste* Operand negativ ist, ist das Ergebnis negativ (oder null).
Daher ist das Ergebnis von `x% = 10` nicht immer zwischen 0 und 9, wenn x negativ sein kann.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS



//SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#  link:../../arithmetic-operators/remainder[Rest]

--
// SEE ALSO SECTION ENDS
