---
title: interrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= interrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Aktiviert Interrupts (nachdem diese mit link:../nointerrupts[nointerrupts()] deaktiviert wurden). Interrupts erlauben bestimmten wichtigen Tasks, im Hintergrund zu laufen
und sind somit per default aktiviert. Wenn Interrupts deaktiviert werden, werden einige Funktionen nicht funktionieren und eingehende Kommunikation wird
möglicherweise ignoriert. Interrupts beeinflussen die Geschwindigkeit und das Timing im Code minimal. Für besonders zeitkritische Codeabschnitte sollten sie
deshalb deaktiviert werden.
[%hardbreaks]


[float]
=== Syntax
`interrupts()`


[float]
=== Parameter
Keine

[float]
=== Rückgabewert
Nichts


--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code zeigt, wie man Interrupts aktiviert und deaktiviert.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // Zeitkritischer Code hier
  interrupts();
  // Restlicher Code hier
}
----
--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../external-interrupts/attachinterrupt[attachInterrupts()]
* #SPRACHE# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SEE ALSO SECTION ENDS
