---
title: noInterrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= noInterrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Deaktiviert Interrupts (Diese können mit link:../interrupts[interrupts()] wieder aktiviert werden). Interrupts erlauben bestimmten wichtigen Tasks, im Hintergrund zu laufen
und sind somit per default aktiviert. Wenn Interrupts deaktiviert werden, werden einige Funktionen nicht funktionieren und eingehende Kommunikation wird
möglicherweise ignoriert. Interrupts beeinflussen die Geschwindigkeit und das Timing im Code minimal. Für besonders zeitkritische Codeabschnitte sollten sie
deshalb deaktiviert werden.
[%hardbreaks]


[float]
=== Syntax
`noInterrupts()`


[float]
=== Parameter
Keine

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code zeigt, wie man Interrupts aktiviert und deaktiviert.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // Zeitkritischer Code hier
  interrupts();
  // Restlicher Code hier
}
----

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE# link:../../external-interrupts/attachinterrupt[attachInterrupts()]
* #LANGUAGE# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SEE ALSO SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
