---
title: noInterrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= noInterrupts()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Deaktiviert Interrupts (Diese können mit link:../interrupts[interrupts()] wieder aktiviert werden). Interrupts erlauben bestimmten wichtigen Tasks, im Hintergrund zu laufen
und sind somit per default aktiviert. Wenn Interrupts deaktiviert werden, werden einige Funktionen nicht funktionieren und eingehende Kommunikation wird
möglicherweise ignoriert. Interrupts beeinflussen die Geschwindigkeit und das Timing im Code minimal. Für besonders zeitkritische Codeabschnitte sollten sie
deshalb deaktiviert werden.
[%hardbreaks]


[float]
=== Syntax
`noInterrupts()`


[float]
=== Parameter
Keine.


[float]
=== Rückgabewert
Nichts.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Der Code zeigt, wie man Interrupts aktiviert und deaktiviert.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // Zeitkritischer Code hier
  interrupts();
  // Restlicher Code hier
}
----
--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../external-interrupts/attachinterrupt[attachInterrupts()]
* #SPRACHE# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
