---
title: bitClear()
categories: [ "Functions" ]
subCategories: [ "Bits and Bytes" ]
---





= bitClear()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Löscht den Wert (Schreibt 0) eines Bits einer Zahlen-Variable.
[%hardbreaks]


[float]
=== Syntax
`bitClear(x, n)`


[float]
=== Parameter
`x`: Die Zahlenvariable, deren Wert gelöscht werden soll. +
`n`: Welches Bit gelöscht werden soll; Startet bei 0 für das least-significant (rechteste) Bit.

[float]
=== Rückgabewert
`x`: Der Wert der numerischen Variablen nach dem Löschen des Bits an Position `n`.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
Gibt das Ergebnis von `bitClear (x, n)` aus und verwendet zwei vorgegebenen ganzen Zahlen. Die binäre Darstellung von 6 ist 0110. Wenn also `n=1` ist, wird das zweite Bit von rechts auf 0 gesetzt. Danach bleibt 0100 in binär, so dass 4 zurückgegeben wird.

[source,arduino]
----
void setup() {
  Serial.begin(9600);
  while (!Serial) {
    ; // Wartet, bis die serielle Schnittstelle hergestellt ist. Wird nur für den nativen USB-Anschluss benötigt.
  }

  int x = 6;
  int n = 1;
  Serial.print(bitClear(x, n)); // Drucke die Ausgabe von bitClear(x,n) auf den seriellen Monitor.
}

void loop() {
}
----
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET



// SEE ALSO SECTION
// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
