---
title: Übergeordneter Titel der Entität
categories: [ "Functions" ]
subCategories: [ "Name der Unterkategorie" ]
---
// ARDUINO SPRACHE REFERENCE TAG (oben)   ►►►►► IMMER IN DIE DATEI EINFÜGEN ◄◄◄◄◄
// Titel wird im Index aller Referenzbegriffe angezeigt
// Kategorien: Wähle zwischen `Structure`, `Variable` oder `Function`
// Die Unterkategorie innerhalb der im Index verfügbaren ("Digital I/O", "Arithmetic Operators")





// SEITENTITEL   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄
= Übergeordneter Titel der Entität()


// ÜBERSICHTSABSCHNITT BEGINNT
[#overview]
--

[float]
=== Beschreibung
// Beschreiben, wofür diese Gruppe von Referenzbegriffen verwendet wird. ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄
Wird für die Kommunikation zwischen dem Arduino-Board und einem Computer oder underen Geräten verwendet. Alle Arduino-Karten haben mindestens eine serielle Schnittstelle (auch UART oder USART genannt): Seriell.
Der Arduino kommuniziert über die digitalen Pins 0 (RX) und 1 (TX) sowie mit dem Computer über USB. Wenn diese Funktionen verwendet werden, können daher nicht die Pins 0 und 1 für die digitale Eingabe oder
Ausgabe verwendet werden. +
Du kannst den eingebauten seriellen Monitor der Arduino-Umgebung verwenden, um mit einem Arduino-Board zu kommunizieren. Klicke in der Symbolleiste auf die Schaltfläche für den seriellen Monitor,
und wähle dieselbe Baudrate aus, die für den Aufruf von `begin()` verwendet wurde.
[%hardbreaks]
Der *Arduino Mega* hat drei zusätzliche serielle Ports: `Seriell1` auf den Pins 19 (RX) und 18 (TX), `Seriell2` auf den Pins 17 (RX) und 16 (TX), `Seriall3` auf den Pins 15 (RX) und 14 (TX).
Um diese Pins für die Kommunikation mit dem PC zu verwenden, benötigst du einen zusätzlichen USB-zu-Seriell-Adapter, da sie nicht an den USB-an-Seriell-Adapter des Mega angeschlossen sind.
Um mit einem externen seriellen TTL-Gerät zu kommunizieren, verbinde den TX-Pin mit dem RX-Pin des Geräts, den RX mit dem TX-Pin des Geräts und die Masse des Mega mit der Masse des Geräts.
(Verbinde diese Pins nicht direkt mit einer seriellen RS232-Schnittstelle. Diese arbeiten mit +/- 12 V und können das Arduino-Board beschädigen.)
[%hardbreaks]
Der *Arduino DUE* verfügt über drei zusätzliche serielle 3.3V-TTL-Ports: `Seriall1` auf den Pins 19 (RX) und 18 (TX); `Seriell2` auf den Pins 17 (RX) und 16 (TX), `Seriall3` auf den Pins 15 (RX) und 14 (TX).
Die Pins 0 und 1 sind auch mit den entsprechenden Pins des seriellen ATmega16U2-USB-zu-TTL-Chips verbunden, der mit dem USB-Debug-Port verbunden ist.
Zusätzlich gibt es einen nativen seriellen USB-Port auf dem SAM3X chip (SerialUSB).
[%hardbreaks]
Das *Arduino Leonardo* Board benutzt `Seriall1` zur Kommunikation über TTL (5V) seriell auf den Pins 0 (RX) und 1 (TX). `Seriell1` ist für die USB-CDC-Kommunikation reserviert.
Weitere Informationen findest du auf der Leonardo-Einführungsseite und der Hardware-Seite.

--
// ÜBERSICHTSABSCHNITT ENDET




// FUNKTIONSABSCHNITT STARTET
[#functions]
--

'''

[float]
=== Funktionen
// Auflisten aller Funktionen in diesem Referenz-übergeordneten Element. ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄
http://arduino.cc[if] (Serial) +
http://arduino.cc[available()] +
http://arduino.cc[begin()] +
http://arduino.cc[end()] +
http://arduino.cc[find()] +
http://arduino.cc[findUntil()] +
http://arduino.cc[flush()] +
http://arduino.cc[parseFloat()] +
http://arduino.cc[parseInt()] +
http://arduino.cc[peek()] +
http://arduino.cc[print()] +
http://arduino.cc[println()] +
http://arduino.cc[read()] +
http://arduino.cc[readBytes()] +
http://arduino.cc[readBytesUntil()] +
http://arduino.cc[setTimeout()] +
http://arduino.cc[write()] +
http://arduino.cc[serialEvent()]

'''

--
// FUNKTIONSABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT STARTET
[#seealso]
--

[float]
=== Siehe auch
// Verknüpfe relevanten Inhalt nach Kategorie, z. B. andere Referenzbegriffe (Bitte füge den Tag #SPRACHE# hinzu).
// Für Definitionen bitte das Tag #DEFINITION# hinzufügen und für Beispiele für Projekte und Tutorials
// das Tag #BEISPIEL# hinzufügen. ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[role="language"]
// Wenn du eine Verknüpfung zu einem anderen Referenzbegriff oder allgemein zu einer relativen Verknüpfung herstellen möchtest, verwende die unten gezeigte Syntax.
// Bitte beachte, dass das Dateiformat nach Attributen subsitiert wird.
// Bitte beachte, dass Leerzeichen, die in Ordner-/Dateinamen gefunden werden, immer durch %20 ersetzt werden müssen.
// Der gesamte Link zu den Referenzseiten muss unabhängig von den Ordnern und Dateien in diesem Repository klein geschrieben werden.
* #SPRACHE# link:../AsciiDoc_Template-Single_Entity[Einzelne Einheit]
* #SPRACHE# link:../../AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary[AsciiDoc Vorlagen]

[role="definition"]
// Bitte beachte, dass alle externen Links in einem neuen Fenster/Tab geöffnet werden müssen, indem ^ vor den letzten eckigen Klammern hinzugefügt wird
* #DEFINITION# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
// Bitte beachte, dass alle externen Links in einem neuen Fenster/Tab geöffnet werden müssen, indem ^ vor den letzten eckigen Klammern hinzugefügt wird
* #BEISPIEL# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// SIEHE-AUCH-ABSCHNITT ENDET
