---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "Random Numbers" ]
---





= randomSeed(seed)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`randomSeed ()` initialisiert den Pseudozufallszahlengenerator, wodurch er an einem beliebigen Punkt in seiner Zufallsfolge startet.
Diese Sequenz ist, obwohl sie sehr lang und zufällig ist, immer dieselbe.

Wenn es für eine von `random ()` erzeugte Folge von Werten wichtig ist, dass diese bei nachfolgenden Ausführungen eines Skecthes unterschiedlich ist,
verwende `randomSeed()`, um den Zufallszahlengenerator mit einer ziemlich zufälligen Eingabe zu initialisieren, z. B. `analogRead()`auf einem nicht verbundenen Pin.

Umgekehrt kann es gelegentlich nützlich sein, Pseudozufallssequenzen zu verwenden, die sich genau wiederholen.
Dies kann durch Aufrufen von `randomSeed ()` mit einer festen Zahl erreicht werden, bevor die Zufallssequenz gestartet wird.
[%hardbreaks]


[float]
=== Parameter
`seed` - eine Zahl übergeben, um die Pseudozufallssequenz zu initialisieren (long).

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code generiert eine Pseudo-Zufallszahl und sendet die erzeugte Nummer an die serielle Schnittstelle.

[source,arduino]
----
long randNumber;

void setup() {
  Serial.begin(9600);
  randomSeed(analogRead(0));
}

void loop() {
  randNumber = random(300);
  Serial.println(randNumber);
  delay(50);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS