---
title: "c_str()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= c_str()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Konvertiert den Inhalt einer Zeichenfolge als nullterminierte Zeichenfolge im C-Stil. Beachte, dass dies direkten Zugriff auf den internen `String`-Puffer bietet und mit Vorsicht verwendet werden sollte.
Insbesondere sollte die Zeichenfolge niemals über den zurückgegebenen Zeiger geändert werden.
Wenn du das `String`-Objekt ändern willst oder wenn es zerstört wird, wird ein zuvor von `c_str()` zurückgegebener Zeiger ungültig und sollte nicht mehr verwendet werden.

[%hardbreaks]


[float]
=== Syntax
[source,arduino]

`myString.c_str()`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
Ein Zeiger auf die C-Style-Version des aufrufenden Strings.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
