---
title: "compareTo()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= compareTo()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Vergleicht zwei Strings und testet, ob einer vor oder nach dem anderen kommt oder ob sie gleich sind.
Die Zeichenfolgen werden zeichenweise verglichen, wobei die ASCII-Werte der Zeichen verwendet werden.
Das bedeutet zum Beispiel, dass `'a'` vor `'b'` liegt, aber nach `'A'`. Zahlen stehen vor Buchstaben.

[%hardbreaks]


[float]
=== Syntax
`myString.compareTo(myString2)`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`myString2`: Eine andere Variable vom Typ `String`. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
`Eine negative Zahl`: Wenn `myString` vor `myString2` steht. +
`0`: Wenn `myString` gleich `myString2` ist. +
`Eine positive Zahl`: Wenn `myString` nach `myString2` kommt.
--

// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
