---
title: "indexOf()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= indexOf()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Sucht ein Zeichen oder eine Zeichenfolge in einer anderen Zeichenfolge. Sucht standardmäßig vom Anfang des Strings, kann aber auch von einem bestimmten Index aus beginnen.
Ermöglicht das Auffinden aller Instanzen des Zeichens oder der Zeichenfolge.


[%hardbreaks]


[float]
=== Syntax
`myString.indexOf(val)` +
`myString.indexOf(val, from)`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`.+
`val`: Der Wert, nach dem gesucht werden soll. Erlaubte Datentypen: `char` oder `String`. +
`from`: Der Index, von dem aus die Suche gestartet werden soll.


[float]
=== Rückgabewert
Der Index des Werts innerhalb des Strings oder -1, falls nicht gefunden.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
