---
title: "lastIndexOf()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= lastIndexOf()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Sucht ein Zeichen oder eine Zeichenfolge in einer anderen Zeichenfolge. Sucht standardmäßig vom Ende des Strings aus, kann aber auch von einem bestimmten Index aus rückwärts arbeiten.
Ermöglicht das Auffinden aller Instanzen des Zeichens oder der Zeichenfolge.

[%hardbreaks]


[float]
=== Syntax
`myString.lastIndexOf(val)` +
`myString.lastIndexOf(val, from)`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`val`: Der Wert, nach dem gesucht werden soll. Erlaubte Datentypen: `char` oder `String`. +
`from`: Der Index des letzen Vorkommnisses des gesuchten Werts.


[float]
=== Rückgabewert
Der Index von `val` innerhalb des Strings oder -1, falls nicht gefunden.

--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
