---
title: "remove()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= remove()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Ändert einen `String`, der die Zeichen aus dem angegebenen Index bis zum Ende des Strings oder aus dem bereitgestellten Index entfernt, um die Anzahl der Indizes zu zählen.

[%hardbreaks]


[float]
=== Syntax
`myString.remove(index)` +
`myString.remove(index, count)`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`index`: Eine Variable vom Typ `unsigned int`. Erlaubte Datentypen: `unsigned int`. +
`count`: Eine Variable vom Typ `unsigned int`. Erlaubte Datentypen: `unsigned int`.


[float]
=== Rückgabewert
Nichts.

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es bei dem Beispielcode geht, und füge den entsprechenden Code hinzu. ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
[source,arduino]
----
String greeting = "hello";
greeting.remove(2, 2);  // greeting enthält jetzt "heo"
----
[%hardbreaks]
--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
