---
title: "replace()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= replace()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Mit der Funktion `String.replace()` kannst du alle Instanzen eines bestimmten Zeichens durch ein anderes Zeichen ersetzen.
Du kannst auch `replace()` verwenden, um Teilstrings eines Strings durch einen anderen Teilstring zu ersetzen.

[%hardbreaks]


[float]
=== Syntax
`myString.replace(substring1, substring2)`


[float]
=== Parameter
`myString`: Eine Variable vom Typ `String`. Erlaubte Datentypen: `String`.+
`substring1`: Eine andere Variable vom Typ `String`. Erlaubte Datentypen: `String`. +
`substring2`: Eine andere Variable vom Typ `String`. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
Nichts.
--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
