---
title: "substring()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= substring()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Ruft einen Teilstring eines Strings ab. Der Startindex ist inklusive (das entsprechende Zeichen ist in der Teilzeichenfolge enthalten).
Der optionale Endindex ist jedoch exklusiv (das entsprechende Zeichen ist nicht in der Teilzeichenfolge enthalten).
Wenn der Endindex weggelassen wird, wird der Teilstring bis zum Ende des Strings fortgesetzt.

[%hardbreaks]


[float]
=== Syntax
[source,arduino]

`myString.substring(from)` +
`myString.substring(from, to)`


[float]
=== Parameter
`myString`: Eine Variable vom Typ String

`from`: Der Index, um den Teilstring zu starten

`to` (optional): Der Index, um den Teilstring vorher zu beenden


[float]
=== Gibt zurück
Der Teilstring.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SEE ALSO SECTION ENDS
