---
title: "toDouble()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= toDouble()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Wandelt einen gültigen String in ein Double um. Die Eingabezeichenfolge sollte mit einer Ziffer beginnen.
Wenn der String Nicht-Zahlen als Zeichen enthält, wird die Konvertierung abgebrochen.
Beispielsweise werden die Strings "123.45", "123" und "123fish" in 123.45, 123.00 und 123.00 konvertiert.
Beachte, dass "123.456" mit 123.46 approximiert wird. Beachte auch, dass Floats nur eine Genauigkeit von 6-7 Dezimalstellen haben und längere Strings möglicherweise abgeschnitten werden.

[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
`myString.toDouble()`
----

[float]
=== Parameter
`myString`: Eine Variable vom Typ String


[float]
=== Gibt zurück
`double`

Wenn keine gültige Konvertierung durchgeführt werden konnte, weil der String nicht mit einer Ziffer beginnt, wird eine Null zurückgegeben.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SEE ALSO SECTION ENDS
