---
title: "toFloat()"
categories: [ "Data Types" ]
subCategories: [ "StringObject Function" ]
---





= toFloat()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Konvertiert einen gültigen String in einen Float. Die Eingabezeichenfolge sollte mit einer Ziffer beginnen.
Wenn die Zeichenfolge Nicht-Zahlen als Zeichen enthält, wird die Konvertierung abgebrochen.
Beispielsweise werden die Zeichenfolgen "123.45", "123" und "123fish" in 123.45, 123.00 und 123.00 konvertiert. Beachte, dass "123.456" mit 123.46 approximiert wird.
Beachte auch, dass Floats nur eine Genauigkeit von 6 bis 7 Dezimalstellen haben und längere Zeichenfolgen möglicherweise abgeschnitten werden.

[%hardbreaks]


[float]
=== Syntax
[source,arduino]

`myString.toFloat()`


[float]
=== Parameter
`myString`: Eine Variable vom Typ String


[float]
=== Gibt zurück
`float`

Wenn keine gültige Konvertierung durchgeführt werden konnte, weil die Zeichenfolge nicht mit einer Ziffer beginnt, wird eine Null zurückgegeben.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String-Tutorials^]
--
// SEE ALSO SECTION ENDS
