---
title: Keyboard.println()
---




= Keyboard.println()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Sendet einen Tastenanschlag an einen verbundenen Computer, gefolgt von newline und carriage return.

link:../keyboardbegin[Keyboard.begin()] muss aufgerufen werden, bevor `Keyboard.println()` verwendet werden kann.
[%hardbreaks]


[float]
=== Syntax
`Keyboard.println()` +
`Keyboard.println(character)`+
`Keyboard.println(characters)`


[float]
=== Parameter
`character`: Ein `char` oder `int`, der an den verbundenen Computer gesendet werden soll, gefolgt von newline und carriage return. Erlaubte Datentypen: `char` oder `int`. +
`characters`: Ein `String`, der an den verbundenen Computer gesendet werden soll, gefolgt von newline und carriage return. Erlaubte Datentypen: `String`.


[float]
=== Rückgabewert
Anzahl an gesendeten Bytes. Datentyp: `size_t`.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

Sendet eine Nachricht über die Keyboard-Bibliothek, wenn der angeschlossene Button gedrückt wird.

[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // Pin 2 wird ein Inputpin mit Pullup-Widerstand.
  // Pin 2 ist damit immer high, bis er auf Ground
  // verbunden wird:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //Wenn der Button gedrückt wird
  if(digitalRead(2) == LOW){
    //Sende die Nachricht
    Keyboard.println("Hello!");
  }
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn das `Keyboard.println()`-Kommando benutzt wird, übernimmt der Arduino die Tastatur! Stelle sicher, dass du Kontrolle über die Tastatur hast, bevor du das Kommando verwendest.
Ein Button, um die Funktion notfalls zu sperren, ist sinnvoll.

--
// HOW TO USE SECTION ENDS
