---
title: Keyboard.write()
---




= Keyboard.write()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Sendet einen Tastenanschlag an einen verbundenen Computer. Das ist das gleiche wie eine Taste zu drücken und wieder loszulassen.
Gesendet werden können ASCII-Zeichen und link:../keyboardmodifiers[Hotkeys].

Nur ASCII-Zeichen, die auf der Tastatur zu finden sind, werden unterstützt. Z.B. ASCII 8 (Rücktaste) würde funktionieren, ASCII25 (Ersetzungszeichen) nicht.
Wenn Großbuchstaben gesendet werden sollen, sendet `Keyboard.write()` den Shift-Hotkey plus das gewünschte Zeichen. Wenn ein numerischer Wert übergeben wird,
sendet die Funktion das ASCII-Zeichen, z.B. Keyboard.write(97) wird zu 'a'.

Für eine Liste an ASCII-Zeichen siehe http://www.asciitable.com/[ASCIITable.com].
[%hardbreaks]


[float]
=== Syntax
`Keyboard.write(character)`


[float]
=== Parameter
`character`: Ein Char oder Integer, der an den verbundenen Computer gesendet werden kann. Kann in jeder beliebigen Notation eines Chars gesendet werden.
Siehe dazu auch die Beispiele unten.

[source,arduino]
----
Keyboard.write(65);         // Sendet das ASCII-Zeichen 65 oder 'A'
Keyboard.write('A');            // Das Gleiche
Keyboard.write(0x41);       // Das Gleiche in Hexadezimalnotation
Keyboard.write(0b01000001); // Das Gleiche in Binärnotation
----

[float]
=== Rückgabewert
Die Anzahl der gesendeten Bytes. Datentyp: `size_t`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Besipielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄

Sendet ein ASCII-'A' über die Keyboard-Bibliothek, wenn der angeschlossene Button gedrückt wird.

[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // Pin 2 wird ein Inputpin mit Pullup-Widerstand.
  // Pin 2 ist damit immer high, bis er auf Ground
  // verbunden wird:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //Wenn der Button gedrückt wird
  if (digitalRead(2) == LOW){
    //Sende ein ASCII 'A'
    Keyboard.write(65);
  }
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn das `Keyboard.println()`-Kommando benutzt wird, übernimmt der Arduino die Tastatur! Stelle sicher, dass du Kontrolle über die Tastatur hast, bevor du das Kommando verwendest.
Ein Button, um die Funktion notfalls zu sperren, ist sinnvoll.

--
// HOW TO USE SECTION ENDS
