---
title: Keyboard.press()
---




= Keyboard.press()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Wenn die Funktion aufgerufen wird, funktioniert sie, wie wenn eine Taste auf der Computertastatur gedrückt und gehalten wird.
Die Funktion ist sinnvoll, wenn link:../keyboardmodifiers[Hotkeys] verwendet werden sollen. Um den Tastenanschlag zu beenden,
benutze link:../keyboardrelease[Keyboard.release()] oderr link:../keyboardreleaseall[Keyboard.releaseAll()].
Bevor `Keyboard.press()` benutzt werden kann, muss link:../keyboardbegin[Keyboard.begin()] aufgerufen werden.
[%hardbreaks]


[float]
=== Syntax
`Keyboard.press(key)`


[float]
=== Parameter
`key`: Die Taste, die gedrückt werden soll. Erlaubte Datentypen: `char`.


[float]
=== Rückgabewert
Die Anzahl der Tastenanschläge, die gesendet wurden. Datentyp: `size_t`.

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu.   ►►►►► DIESER ABSCHNITT IST VERPFLICHTEND ◄◄◄◄◄
Öffnet ein neues Dokument und wartet, bis dieses offen ist.

[source,arduino]
----
#include <Keyboard.h>

// Benutze diese Option für OSX:
char ctrlKey = KEY_LEFT_GUI;
// Benutze diese Option für Windows und Linux:
//  char ctrlKey = KEY_LEFT_CTRL;

void setup() {
  // Pin 2 wird ein Inputpin mit Pullup-Widerstand.
  // Pin 2 ist damit immer high, bis er auf Ground
  // verbunden wird:
  pinMode(2, INPUT_PULLUP);
  // Initialisiere die Tastatur:
  Keyboard.begin();
}

void loop() {
  while (digitalRead(2) == HIGH) {
    // Tue nichts, solange Pin nicht LOW ist
    delay(500);
  }
  delay(1000);
  // Erstelle ein neues Dokument: (STRG + N)
  Keyboard.press(ctrlKey);
  Keyboard.press('n');
  delay(100);
  Keyboard.releaseAll();
  // Warte, bis sich das Fenster öffnet:
  delay(1000);
}
----

--
// HOW-TO-USE-ABSCHNITT ENDET
