---
title: "<="
title_expanded: Kleiner oder gleich
categories: [ "Structure" ]
subCategories: [ "Comparison Operators" ]
---





= <= Kleiner oder gleich


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Vergleicht die linke Variable mit dem Wert oder der Variablen rechts vom Operator. Gibt `true` zurück, wenn der Operand links kleiner oder gleich dem Operanden rechts ist.
[%hardbreaks]


[float]
=== Syntax
`x <= y;   // Ist true, wenn x kleiner oder gleich y ist und false, wenn x größer als y ist`


[float]
=== Parameter
`x`: Variable. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long`. +
`y`: Variable oder Konstante. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long`.


--
// ÜBERSICHTSABSCHNITT ENDET



// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
if (x <= y) { // Prüft, ob x kleiner oder gleich y ist
  // Tue etwas nur dann, wenn das Vergleichsergebnis wahr ist
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Negative Zahlen sind kleiner als positive Zahlen.
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET




// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
