---
title: delay()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---





= delay()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Unterbricht das Programm für die als Parameter angegebene Zeit (in Millisekunden). (Es gibt 1000 Millisekunden in einer Sekunde.)
[%hardbreaks]


[float]
=== Syntax
`delay(ms)`


[float]
=== Parameter
`ms`: die Anzahl der Millisekunden, die angehalten werden sollen (`unsigned long`)

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code hält das Programm für eine Sekunde an, bevor der Ausgangs-Pin umgeschaltet wird.

[source,arduino]
----
int ledPin = 13; // LED auf Digitalpin 13

void setup() {
  pinMode(ledPin, OUTPUT); // Setzt den digitalen Pin als Ausgang
}

void loop() {
  digitalWrite(ledPin, HIGH); // LED an
  delay(1000);                // Eine Sekunde warten
  digitalWrite(ledPin, LOW);  // LED aus
  delay(1000);                // Eine Sekunde warten
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Während es einfach ist, eine blinkende LED mit der Funktion `delay()` zu erstellen, und viele Sketchn kurze Verzögerungen für Aufgaben wie das Entprellen des Switches verwenden,
hat die Verwendung von `delay()` in einem Sketch erhebliche Nachteile.
Während der Verzögerungsfunktion kann kein anderes Lesen von Sensoren, mathematischen Berechnungen oder Pin-Manipulationen durchgeführt werden, sodass die meisten anderen Aktivitäten zum Erliegen kommen.
Für alternative Ansätze zum Steuern des Timings siehe den link:http://arduino.cc/de/Tutorial/BlinkWithoutDelay[Blinken ohne Verzögerung]-Sketch, welcher über Schleifen die Funktion link:../millis[millis()] abfrägt, bis genügend Zeit vergangen ist.
Erfahrene Programmierer vermeiden normalerweise die Verwendung von `delay()` für das Timing von Ereignissen, die länger als 10 Millisekunden sind, es sei denn, der Arduino-Sketch ist sehr einfach.

Bestimmte Dinge laufen jedoch weiter, während die `delay()`-Funktion den Atmega-Chip steuert, da die `delay()`-Funktion Interrupts nicht deaktiviert.
Die serielle Kommunikation, die am RX-Pin erscheint, wird aufgezeichnet, die Werte für PWM (link:../../analog-io/analogwrite[analogWrite]) und Pin-Status werden beibehalten.
Auch link:../../external-interrupts/attachinterrupt[Interrupts] funktionieren wie sie sollen.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blinken ohne Verzögerung^]

--
// SEE ALSO SECTION ENDS
