---
title: micros()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---





= micros()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Gibt die Anzahl der Mikrosekunden zurück, seit das Arduino-Board das aktuelle Programm gestartet hat.
Diese Zahl läuft nach ca. 70 Minuten über (Nullstellen).
Auf 16-MHz-Arduino-Boards (z. B. Duemilanove und Nano) hat diese Funktion eine Auflösung von vier Mikrosekunden (d. H. Der zurückgegebene Wert ist immer ein Vielfaches von vier).
Auf 8-MHz-Arduino-Boards (z. B. dem LilyPad) hat diese Funktion eine Auflösung von acht Mikrosekunden.
[%hardbreaks]


[float]
=== Syntax
`time = micros()`


[float]
=== Parameter
Nothing

[float]
=== Gibt zurück
Gibt die Anzahl der Mikrosekunden zurück, seit das Arduino-Board das aktuelle Programm gestartet hat. (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code gibt die Anzahl der Mikrosekunden seit dem Beginn des Arduino-Boards zurück.

[source,arduino]
----
unsigned long time;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Time: ");
  time = micros();
  Serial.println(time); // gibt die Zeit seit dem Programmstart aus
  delay(1000);          // Warten Sie eine Sekunde, um keine riesigen Datenmengen zu senden
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Es gibt 1.000 Mikrosekunden in einer Millisekunde und 1.000.000 Mikrosekunden in einer Sekunde.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
