---
title: millis()
categories: [ "Functions" ]
subCategories: [ "Zeit" ]
---

= millis()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Gibt die Anzahl von Millisekunden zurück, seit das Arduino-Board das aktuelle Programm gestartet hat. Diese Zahl läuft nach etwa 50 Tagen über (geht auf Null zurück).
[%hardbreaks]


[float]
=== Syntax
`time = millis()`


[float]
=== Parameter
Nothing

[float]
=== Gibt zurück
Anzahl der Millisekunden seit dem Programmstart (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Der Code liest die Millisekunden seit Beginn des Sketches des Arduino-Boards und gibt diese auf den seriellen Port aus.

[source,arduino]
----
unsigned long time;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Time: ");
  time = millis();
  Serial.println(time);// Gibt die Zeit seit dem Programmstart aus
  delay(1000);         // Eine Sekunde warten, um keine riesigen Datenmengen zu senden
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Bitte beachte, dass der Rückgabewert für `millis()` ein `unsigned long`-Wert ist.
Es können logische Fehler auftreten, wenn ein Programmierer versucht, mit kleineren Datentypen (z. B. `int`) zu rechnen.
Sogar mit Vorzeichen versehene `long`-Werte können auf Fehler stoßen, da ihr Maximalwert die Hälfte des vorzeichenlosen Gegenstücks ist.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blinken ohne Verzögerung^]

--
// SEE ALSO SECTION ENDS
