---
title: Stream.parseInt()
---




= parseInt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`parseInt()` gibt die erste gültige (long) Ganzzahl von der aktuellen Position zurück. Anfangszeichen, die keine Ganzzahlen sind (oder das Minuszeichen), werden übersprungen.

Genauergesagt:

* Anfangszeichen, die keine Ziffern oder Minuszeichen sind, werden übersprungen; +
* Die Analyse stoppt, wenn für einen konfigurierbaren Timeout-Wert keine Zeichen gelesen wurden oder eine Nicht-Ziffer gelesen wird; +
* Wenn zum Timeout keine gültigen Ziffern gelesen wurden, tritt ein (siehe link:../streamsettimeout[Stream.setTimeout()]) auf und 0 wird zurückgegeben;

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.
[%hardbreaks]


[float]
=== Syntax
`stream.parseInt(list)`

`stream.parseInt(''list', char skipchar')`

[float]
=== Parameter
`stream` : Eine Instanz einer Klasse, die von Stream erbt.

`list` : Der Stream, um nach Ints zu suchen (`char`)

`skipChar`: Wird verwendet, um das angegebene Zeichen bei der Suche zu überspringen. Wird beispielsweise verwendet, um den Tausenderteiler zu überspringen.

[float]
=== Gibt zurück
`long`

--
// OVERVIEW SECTION ENDS
