---
title: Stream.readStringUntil()
---




= readStringUntil()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`readStringUntil()` liest Zeichen aus einem Stream in einen `String`. Die Funktion wird beendet, wenn das Abschlusszeichen erkannt wird oder das Zeitlimit überschritten wird (Siehe link:../streamsettimeout[setTimeout()]).

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.
[%hardbreaks]


[float]
=== Syntax
`stream.readString(terminator)`


[float]
=== Parameter
`stream`: Eine Instanz einer Klasse, die von Stream erbt. +
`terminator`: Das zu suchende Zeichen. Erlaubte Datentypen: `char`.


[float]
=== Rückgabewert
Der gesamte `String`, gelesen von einem Stream bis zum Abschlusszeichen.

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Das Abschlusszeichen wird aus dem Stream entfernt.
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET

