---
title: Stream.findUntil()
---




= `findUntil()`


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`findUntil()` liest Daten aus dem Stream, bis die Zielzeichenfolge der angegebenen Länge oder Terminatorzeichenfolge gefunden wurde oder das Zeitlimit überschritten wurde (siehe link:../streamsettimeout[Stream.setTimeout()]).

Die Funktion gibt `true` zurück, wenn ein Zielstring gefunden wird, `false`, wenn das Zeitlimit überschritten wird.

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.
[%hardbreaks]


[float]
=== Syntax
`stream.findUntil(target, terminal)`


[float]
=== Parameter
`stream`: Eine Instanz einer Klasse, die von Stream erbt. +
`target`: Die Zeichenfolge, nach der gesucht werden soll. Erlaubte Datentypen: `char`. +
`terminal`: Die Terminalzeichenfolge bei der Suche. Erlaubte Datentypen: `size_t`.


[float]
=== Rückgabewert
Datentyp: `bool`.

--
// ÜBERSICHTSABSCHNITT ENDET
