---
title: Stream.readBytes()
---




= readBytes()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`readBytes()` liest Zeichen aus einem Stream in einen Puffer. Die Funktion wird beendet, wenn die ermittelte Länge gelesen wurde oder das Zeitlimit überschritten wurde (siehe link:../streamSetTimeout[setTimeout()]).

`readBytes()` gibt die Anzahl der Bytes in den Puffer zurück. Eine 0 bedeutet, dass keine gültigen Daten gefunden wurden.

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.
[%hardbreaks]


[float]
=== Syntax
`stream.readBytes(buffer, length)`


[float]
=== Parameter
`stream` : Eine Instanz einer Klasse, die von Stream erbt.

`buffer` : Der Puffer zum Speichern der Bytes (`char[]` oder `byte[]`)

`length` : Die Anzahl der zu lesenden Bytes `(int)`

[float]
=== Rückgabewert
Die Anzahl der Bytes, die im Puffer abgelegt wurden (`size_t`)

--
// OVERVIEW SECTION ENDS
