---
title: Stream.setTimeout()
---




= setTimeout()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`setTimeout()` legt die maximalen Millisekunden für das Warten auf Stream-Daten fest. Der Standardwert ist 1000 Millisekunden.
Diese Funktion ist Teil der Stream-Klasse und kann von jeder Klasse aufgerufen werden, die von ihr erbt (Wire, Serial usw.).
Weitere Informationen findest du auf der Hauptseite: link:../../stream[Stream-Klasse].
[%hardbreaks]


[float]
=== Syntax
`stream.setTimeout(time)`


[float]
=== Parameter
`stream`: Eine Instanz einer Klasse, die von Stream erbt. +
`time`: Timeout-Dauer in Millisekunden. Erlaubte Datentypen: `long`.

[float]
=== Rückgabewert
Nichts.

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Stream-Funktionen, die den mit `setTimeout()` eingestellten Timeout-Wert verwenden:

* `find()`
* `findUntil()`
* `parseInt()`
* `parseFloat()`
* `readBytes()`
* `readBytesUntil()`
* `readString()`
* `readStringUntil()`

[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== See also

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
