---
title: Stream.readBytesUntil()
---




= readBytesUntil()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`readBytesUntil()` liest Zeichen aus einem Stream in einen Puffer. Die Funktion wird beendet, wenn das Abschlusszeichen erkannt wird, die ermittelte Länge gelesen wurde
oder das Zeitlimit überschritten wurde (siehe link:../streamsettimeout[setTimeout()]). Die Funktion gibt die Zeichen bis zum letzten Zeichen vor dem angegebenen Abschlusszeichen zurück.
Der Terminator selbst wird nicht im Puffer zurückgegeben.

`readBytesUntil()` gibt die Anzahl der Bytes in den Puffer zurück. Eine 0 bedeutet, dass keine gültigen Daten gefunden wurden.

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.
[%hardbreaks]


[float]
=== Syntax
`stream.readBytesUntil(character, buffer, length)`


[float]
=== Parameter
`stream`: Eine Instanz einer Klasse, die von Stream erbt. +
`character`: Das zu suchende Zeichen. Erlaubte Datentypen: `char`. +
`buffer`: Der Puffer zum Speichern der Bytes.  Erlaubte Datentypen: Array von `char` oder `byte`.+
`length`: Die Anzahl der zu lesenden Bytes. Erlaubte Datentypen: `size_t`.


[float]
=== Rückgabewert
Die Anzahl der Bytes, die im Puffer abgelegt wurden. Datentyp: `size_t`.

--
// ÜBERSICHTSABSCHNITT ENDET


// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Das Abschlusszeichen wird aus dem Stream entfernt.
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET
