---
title: Stream.parseInt()
---




= parseInt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`parseInt()` gibt die erste gültige (long) Ganzzahl von der aktuellen Position zurück.

Genauergesagt:

* Die Analyse stoppt, wenn für einen konfigurierbaren Timeout-Wert keine Zeichen gelesen wurden oder eine Nicht-Ziffer gelesen wird; +
* Wenn zum Timeout keine gültigen Ziffern gelesen wurden, tritt ein (siehe link:../streamsettimeout[Stream.setTimeout()]) auf und 0 wird zurückgegeben;

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.
[%hardbreaks]


[float]
=== Syntax
`stream.parseInt()` +
`stream.parseInt(lookahead)` +
`stream.parseInt(lookahead, ignore)`

[float]
=== Parameter
`stream` : Eine Instanz einer Klasse, die von Stream erbt.

`lookahead`: Der Modus, mit dem im Stream nach vorne nach einer Ganzzahl gesucht wird. Erlaubte Datentypen: `LookaheadMode`.
Erlaubte `lookahead`-Werte:

* `SKIP_ALL`: Alle Zeichen außer Ziffern oder einem Minuszeichen werden beim Scannen des Streams nach einer Ganzzahl ignoriert. Dies ist der Standardmodus.
* `SKIP_NONE`: Nichts wird übersprungen und der Stream wird nur dann berührt, wenn das erste wartende Zeichen gültig ist.
* `SKIP_WHITESPACE`: Nur Registerkarten, Leerzeichen, Zeilenvorschub und Carriage Returns werden übersprungen.

`ignore`: Wird verwendet, um das angegebene Zeichen bei der Suche zu überspringen. Wird beispielsweise verwendet, um Tausenderteiler zu überspringen. Zulässige Datentypen: `char`

[float]
=== Rückgabewert
`long`

--
// OVERVIEW SECTION ENDS
