---
title: "/* */"
title_expanded: Kommentarblock
categories: [ "Structure" ]
subCategories: [ "Weitere Syntax" ]
---





= /* */ Kommentarblock


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
*Kommentare* sind Zeilen im Programm, die dazu dienen, sich oder andere über die Funktionsweise des Programms zu informieren.
Sie werden vom Compiler ignoriert und nicht in den Prozessor exportiert, sodass sie keinen Platz im Flash-Speicher des Mikrocontrollers beanspruchen.
Der einzige Zweck von Kommentaren besteht darin, zu helfen (zu verstehen oder sich daran zu erinnern) oder andere über die Funktionsweise des Programms zu informieren.
[%hardbreaks]

Der Anfang eines *Blockkommentars* oder eines *mehrzeiligen Kommentars* ist mit dem Symbol `/\*` gekennzeichnet und das Symbol `*/` markiert sein Ende.
Diese Art von Kommentar wird aufgerufen, da sich dieser über mehrere Zeilen erstrecken kann. Sobald der Compiler das `/\*` liest, ignoriert er alles, was folgt, bis er ein `*/` findet.

// NOTE TO THE EDITOR: The '\' before the '*' in certain places are to escape the '*' from making the text bolder.
// In places were '\' is not used before '*', it is not actually required.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
[source,arduino]
----
/* Dies ist ein gültiger Kommentar */

/*
  Blink
  Schaltet eine LED für eine Sekunde ein und dann für eine Sekunde wiederholt aus.

  Dieser Beispielcode ist im öffentlichen Bereich.
  (Ein weiterer gültiger Kommentar)
*/

/*
  if (gwb == 0) {   // Ein einzeiliger Kommentar ist in einem mehrzeiligen Kommentar in Ordnung
    x = 3;           /* aber kein weiterer mehrzeiliger Kommentar - das ist ungültig */
  }
// Vergiss nicht den abschließenden Kommentar - Die Klammern müssen zusammenpassen!
*/
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Beim Experimentieren mit Code ist das Herauskommentieren von Programmteilen eine bequeme Möglichkeit, fehlerhafte Zeilen zu entfernen.
Dadurch bleiben die Zeilen im Code erhalten, werden jedoch in Kommentare umgewandelt, sodass der Compiler sie einfach ignoriert.
Dies kann besonders nützlich sein, wenn du versuchst, ein Problem zu finden, oder wenn ein Programm die Kompilierung ablehnt und
der Compilerfehler kryptisch oder nicht hilfreich ist.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch
[role="language"]

--
// SEE ALSO SECTION ENDS
