---
title: "{}"
title_expanded: curly braces
categories: [ "Structure" ]
subCategories: [ "Weitere Syntax" ]
---




= {} Curly Braces


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Geschweifte Klammern (auch als "geschweifte Klammern" oder "geschweifte Klammern" bezeichnet) sind ein Hauptbestandteil der Programmiersprache C ++.
Sie werden in mehreren verschiedenen Konstrukten verwendet (siehe unten), was für Anfänger manchmal verwirrend sein kann.
Auf eine öffnende geschweifte Klammer `{` muss immer eine schließende geschweifte Klammer `}` folgen.
Dies ist eine Bedingung, die oft als ausgeglichene Klammern bezeichnet wird.
Die Arduino IDE (Integrated Development Environment) enthält eine praktische Funktion zum Überprüfen des Gleichgewichts von geschweiften Klammern.
Wähle einfach eine geschweifte Klammer aus oder klicke auf die Einfügemarke unmittelbar nach einer geschweiften Klammer. Der logische Begleiter wird hervorgehoben.
[%hardbreaks]
Anfänger und Programmierer, die aus der BASIC-Sprache zu C ++ kommen, finden Klammern oft verwirrend oder abschreckend.
Letztendlich aber, ersetzen dieselben geschweiften Klammern die RETURN-Anweisung in einer Subroutine (Funktion), die ENDIF-Anweisung in einer Bedingung und die NEXT-Anweisung in einer FOR-Schleife.
[%hardbreaks]
Unausgeglichene geschweifte Klammern können oft zu kryptischen, undurchdringlichen Compiler-Fehlern führen, die in einem großen Programm manchmal schwer zu finden sind.
Aufgrund ihrer unterschiedlichen Verwendungsmöglichkeiten sind Klammern auch für die Syntax eines Programms unglaublich wichtig.
Wenn Sie eine oder zwei Zeilen einer Klammer verschieben, hat dies oft einen dramatischen Einfluss auf die Bedeutung eines Programms.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
Die Hauptanwendungen von geschweiften Klammern sind in den folgenden Beispielen aufgeführt.


[float]
==== Funktionen

[source,arduino]
----
void myFunction(Datentyp Argument){
  // Beliebige Anweisung(en)
}
----
[%hardbreaks]


[float]
==== Schleifen

[source,arduino]
----
while (Boolean-Ausdruck) {
   // Beliebige Anweisung(en)
}

do {
  // Beliebige Anweisung(en)
} while (Boolean-Ausdruck);

for (Initialisierung; Schlussbedingung; inkrementierender Ausdruck) {
  // Beliebige Anweisung(en)
}
----
[%hardbreaks]




[float]
==== Bedingte Anweisungen

[source,arduino]
----
if (Boolean-Ausdruck) {
  // Beliebige Anweisung(en)
}
else if (Boolean-Ausdruck) {
  // Beliebige Anweisung(en)
}
else {
  // Beliebige Anweisung(en)
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch
[role="language"]

--
// SEE ALSO SECTION ENDS
