---
title: "#define"
title_expanded: define
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= #define


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`#define` ist eine nützliche C ++ - Komponente, mit der der Programmierer einem konstanten Wert einen Namen geben kann, bevor das Programm kompiliert wird.
Definierte Konstanten in Arduino belegen keinen Programmspeicherplatz auf dem Chip.
Der Compiler ersetzt zur Kompilierzeit Verweise auf diese Konstanten durch den definierten Wert.
[%hardbreaks]

Dies kann jedoch einige unerwünschte Nebenwirkungen haben, wenn zum Beispiel ein konstanter Name, der #defined wurde, in einer anderen Konstanten- oder Variablenname enthalten ist.
In diesem Fall würde der Text durch die #definierte Nummer (oder den Text) ersetzt.
[%hardbreaks]

Generell sollte das `link:../../../variables/variable-scope-qualifiers/const[const]`-Schlüsselwort für die Definition von Konstanten bevorzugt und anstelle von `#define` verwendet werden.
[%hardbreaks]

[float]
=== Syntax
`#define Konstantenname Wert`


[float]
=== Parameter
`Konstantenname`: Der Name des zu definierenden Makros. +
`Wert`: Der Wert, der dem Makro zugewiesen werden soll.


--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
#define ledPin 3
// Der Compiler ersetzt alle Erwähnungen von ledPin zur Kompilierzeit durch den Wert 3.
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Es gibt kein Semikolon nach der Anweisung #define. Wenn eines hinzufügt wird, so wirft der Compiler weiter unten auf der Seite kryptische Fehler aus.

[source,arduino]
----
#define ledPin 3;    // Das ist ein Fehler
----

Wenn ein Gleichheitszeichen nach der Anweisung #define einfügt wird, wird ebenfalls ein kryptischer Compiler-Fehler weiter unten auf der Seite generiert.

[source,arduino]
----
#define ledPin = 3  // Das ist auch ein Fehler
----
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET




// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#	link:../../../variables/variable-scope\--qualifiers/const[const]
* #SPRACHE#	link:../../../variables/constants/constants[Konstanten]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
