---
title: "#include"
title_expanded: include
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= #include


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`#include` wird verwendet, um externe Bibliotheken in den Sketch aufzunehmen.
Dadurch erhält der Programmierer Zugriff auf eine große Gruppe von Standard-C-Bibliotheken (Gruppen vorgefertigter Funktionen) sowie auf speziell für Arduino geschriebene Bibliotheken.
[%hardbreaks]

Die Hauptreferenzseite für AVR C-Bibliotheken (AVR ist eine Referenz auf die Atmel-Chips, auf denen der Arduino basiert) ist http://www.nongnu.org/avr-libc/user-manual/modules.html[hier^].
[%hardbreaks]

Beachten Sie, dass `#include`, ähnlich wie link:../define[`#define`] kein Semikolon-Abschlusszeichen enthält und der Compiler bei der Eingabe kryptische Fehlermeldungen ausgibt.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
Dieses Beispiel fügt eine Bibliothek ein, in der Daten anstelle von _RAM-Speicher_ in den Programmspeicher (_flash_) eingefügt werden.
Dies spart den RAM-Speicherplatz für dynamische Speicheranforderungen und macht große Nachschlagetabellen praktischer.


[source,arduino]
----
#include <avr/pgmspace.h>

prog_uint16_t myConstants[] PROGMEM = {0, 21140, 702  , 9128,  0, 25764, 8456,
0,0,0,0,0,0,0,0,29810,8968,29762,29762,4500};
----


--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]


--
// SEE ALSO SECTION ENDS