---
title: "#include"
title_expanded: include
categories: [ "Structure" ]
subCategories: [ "Weitere Syntax" ]
---





= #include


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`#include` wird verwendet, um externe Bibliotheken in den Sketch aufzunehmen.
Dadurch erhält der Programmierer Zugriff auf eine große Gruppe von Standard-C-Bibliotheken (Gruppen vorgefertigter Funktionen) sowie auf speziell für Arduino geschriebene Bibliotheken.
[%hardbreaks]

Die Hauptreferenzseite für AVR C-Bibliotheken (AVR ist eine Referenz auf die Atmel-Chips, auf denen der Arduino basiert) ist http://www.nongnu.org/avr-libc/user-manual/modules.html[hier^].
[%hardbreaks]

Beachte, dass `#include`, ähnlich wie link:../define[`#define`] kein Semikolon-Abschlusszeichen enthält und der Compiler bei der Eingabe kryptische Fehlermeldungen ausgibt.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
Dieses Beispiel enthält die Servobibliothek, sodass ihre Funktionen zur Steuerung eines Servomotors verwendet werden können.


[source,arduino]
----
#include <Servo.h>
Servo myservo;  // Servoobjekt erstellen, um einen Servomotor zu steuern
void setup() {
  myservo.attach(9);  // Bindet den Servomotor an Pin 9 an das Servoobjekt
}
void loop() {
  for (int pos = 0; pos <= 180; pos += 1) { // Geht von 0 Grad bis 180 Grad
    // in 1 Grad-Stufen
    myservo.write(pos);              // Servo anweisen, in Position von Variable 'pos' zu gehen
    delay(15);                       // Wartet 15ms, bis der Servomotor die Position erreicht hat
  }
  for (int pos = 180; pos >= 0; pos -= 1) { // Geht von 180 Grad bis 0 Grad
    myservo.write(pos);              // Servo anweisen, in Position von Variable 'pos' zu gehen
    delay(15);                       // Wartet 15ms, bis der Servomotor die Position erreicht hat
  }
}
----


--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]


--
// SEE ALSO SECTION ENDS
