---
title: ";"
title_expanded: Semikolon
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= ; Semikolon


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Wird verwendet, um eine Anweisung zu beenden.
[%hardbreaks]

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode
`int a = 13;` +
`float b = 17.1;`


[float]
=== Anmerkungen und Warnungen
Wenn du vergisst, eine Zeile in einem Semikolon zu beenden, wird ein Compiler-Fehler ausgegeben.
Der Fehlertext kann offensichtlich sein und sich auf ein fehlendes Semikolon beziehen oder nicht.Wenn ein undurchdringlicher oder
scheinbar unlogischer Compiler-Fehler auftritt, ist eines der ersten zu überprüfenden Dinge ein fehlendes Semikolon in unmittelbarer Nähe
vor der Zeile, in der sich der Compiler beschwert hat.
[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET




// SIEHE-AUCH-ABSCHNITT SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
