---
title: "//"
title_expanded: Einzeiliger Kommentar
categories: [ "Structure" ]
subCategories: [ "Weitere Syntax" ]
---





= // Einzeiliger Kommentar


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
*Kommentare* sind Zeilen im Programm, die dazu dienen, sich oder andere über die Funktionsweise des Programms zu informieren.
Sie werden vom Compiler ignoriert und nicht in den Prozessor exportiert, sodass sie keinen Platz im Flash-Speicher des Mikrocontrollers beanspruchen.
Der einzige Zweck von Kommentaren besteht darin, zu helfen (zu verstehen oder sich daran zu erinnern) oder andere über die Funktionsweise des Programms zu informieren.
[%hardbreaks]

Ein *einzeiliger Kommentar* beginnt mit `//` (zwei nebeneinanderliegende Schrägstriche).
Dieser Kommentar endet automatisch am Ende einer Zeile. Alles, was bis zum Ende einer Zeile auf `//` folgt, wird vom Compiler ignoriert.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
Es gibt zwei Möglichkeiten, eine Zeile als Kommentar zu kennzeichnen:

[source,arduino]
----
// An Pin 13 ist an den meisten Arduino-Boards eine LED angeschlossen.
int led = 13;

digitalWrite(led, HIGH); // LED einschalten (HIGH ist der Spannungspegel)
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Beim Experimentieren mit Code ist das Herauskommentieren von Programmteilen eine bequeme Möglichkeit, fehlerhafte Zeilen zu entfernen.
Dadurch bleiben die Zeilen im Code erhalten, werden jedoch in Kommentare umgewandelt, sodass der Compiler sie einfach ignoriert.
Dies kann besonders nützlich sein, wenn Sie versuchen, ein Problem zu finden, oder wenn ein Programm die Kompilierung ablehnt und der Compilerfehler kryptisch oder nicht hilfreich ist.
[%hardbreaks]


--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
