---
title: "<<"
title_expanded: bitshift left
categories: [ "Structure" ]
subCategories: [ "Bitwise Operators" ]
---





= << Bitshift Left


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Der Left-Shift-Operator `<<` bewirkt, dass die Bits des linken Operanden um die vom rechten Operanden angegebene Anzahl von Positionen *nach links* verschoben werden.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
variable << number_of_bits;
----

[float]
=== Parameter
`variable`: *Erlaubte Datentypen:* byte, int, long +
`number_of_bits`: Eine Zahl < = 32. *Erlaubte Datentypen:* int

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int a = 5;      // Binär: 0000000000000101
int b = a << 3; // Binär: 0000000000101000, oder 40 als Dezimal
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Wenn Sie einen Wert x um y Bits (x << y) verschieben, gehen die am weitesten links liegenden y Bits in x verloren.

[source,arduino]
----
int x = 5; // Binär: 0000000000000101
int y = 14;
int result = x << y; // Binär: 0100000000000000 - Die erste 1 von 101 wurde verworfen
----

Wenn Sie sicher sind, dass keine der Einsen in einem Wert in Vergessenheit gerät, ist ein einfacher Weg, sich den Operator für die linke Verschiebung vorzustellen,
dass er den linken Operanden mit 2 multipliziert, um die Potenz des rechten Operanden zu erreichen.
Um beispielsweise Potenzen von 2 zu erzeugen, können die folgenden Ausdrücke verwendet werden:

[source,arduino]
----
   Operation  Ergebnis
   ---------  ------
    1 <<  0      1
    1 <<  1      2
    1 <<  2      4
    1 <<  3      8
    ...
    1 <<  8    256
    1 <<  9    512
    1 << 10   1024
    ...
----

Das folgende Beispiel kann verwendet werden, um den Wert eines empfangenen Bytes an den seriellen Monitor auszugeben.
Verwende den linken Umschaltoperator, um das Byte von unten (LSB) nach oben (MSB) zu verschieben und seinen binären Wert auszugeben:

[source,arduino]
----
// Gibt den binären Wert (1 oder 0) des Bytes aus
void printOut1(int c) {
  for (int bits = 7; bits > -1; bits--) {
    // Vergleiche die Bits 7-0 im Byte
    if (c & (1 << bits)) {
      Serial.print("1");
    }
    else {
      Serial.print("0");
    }
  }
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




//SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

[role="example"]
* #BEISPIEL# https://www.arduino.cc/playground/Code/BitMath[BitMath-Tutorial^]

--
//SEE ALSO SECTION ENDS

