---
title: "~"
title_expanded: Bitweises NICHT
categories: [ "Structure" ]
subCategories: [ "Bitweise Operatoren" ]
---





= ~ Bitweises NICHT


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Der bitweise NOT-Operator in C ++ ist das Tilde-Zeichen `~`. Im Gegensatz zu `&` und `|` wird der bitweise NOT-Operator auf einen einzelnen Operanden rechts davon angewendet.
Bitweises NOT ändert jedes Bit in sein Gegenteil: 0 wird 1 und 1 wird 0.
[%hardbreaks]

In anderen Worten:

    0  1    operand1
    -----
    1  0   ~operand1
[%hardbreaks]
--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int a = 103; // Binär: 0000000001100111
int b = ~a;  // Binär: 1111111110011000 = -104
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Möglicherweise bist du überrascht, als Ergebnis dieses Vorgangs eine negative Zahl wie -104 zu sehen.
Dies liegt daran, dass das höchste Bit in einer `int`-Variablen das sogenannte Vorzeichenbit ist.
Wenn das höchste Bit 1 ist, wird die Zahl als negativ interpretiert.
Diese Kodierung von positiven und negativen Zahlen wird als Zweierkomplement bezeichnet.
Weitere Informationen finden sich im Wikipedia-Artikel über das https://de.wikipedia.org/wiki/Zweierkomplement[Zweierkomplement^].

Nebenbei bemerkt ist es interessant zu wissen, dass ~x für jede ganze Zahl x das gleiche ist wie -x-1.

Das Vorzeichenbit in einem vorzeichenbehafteten ganzzahligen Ausdruck kann manchmal zu unerwünschten Überraschungen führen.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS



// SEE ALSO BEGINS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

[role="example"]
* #BEISPIEL# https://www.arduino.cc/playground/Code/BitMath[BitMath-Tutorial^]

--
//SEE ALSO SECTION ENDS
