---
title: "+"
title_expanded: Addition
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---





= + Addition


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
*Addition* ist eine der vier primären Rechenoperationen. Der Operator `+` (plus) bearbeitet zwei Operanden, um die Summe zu erzeugen.
[%hardbreaks]


[float]
=== Syntax
`sum = operand1 + operand2`


[float]
=== Parameter
`sum`: Variable. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long`. +
`operand1`: Variable oder Konstante. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long`. +
`operand2`: Variable oder Konstante. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long`.
--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int a = 5;
int b = 10;
int c = 0;
c = a + b; // Die Variable 'c' erhält einen Wert von 15, nachdem diese Anweisung ausgeführt wurde
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
1. Die Additionsoperation kann überlaufen, wenn das Ergebnis größer ist als das Ergebnis, das im Datentyp gespeichert werden kann (z. B. ergibt das Hinzufügen von 1 zu einer Ganzzahl mit dem Wert 32,767 den Wert -32,768).

2. Wenn eine der Zahlen (Operanden) vom Typ `float` oder vom Typ `double` ist, wird für die Berechnung Fließkomma-Mathematik verwendet.

3. Wenn die Operanden vom Datentyp float / double sind und die Variable, die die Summe speichert, eine Ganzzahl ist, wird nur die Ganzzahl gespeichert, der Bruchteil der Zahl geht verloren.

[source,arduino]
----
float a = 5.5
float b = 6.6;
int c = 0;
c = a + b; // Die Variable 'c' speichert nur den Wert 12 gegenüber der erwarteten Summe von 12,1
----
[%hardbreaks]
--
// HOW-TO-USE-ABSCHNITT ENDET




// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
