---
title: "="
title_expanded: "assignment operator"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---





= = Assignment (single equal sign)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Das einfache Gleichheitszeichen `=` in der Programmiersprache C ++ wird als Zuweisungsoperator bezeichnet.
Es hat eine andere Bedeutung als in der Algebra, wo es eine Gleichung oder Gleichheit angibt.
Der Zuweisungsoperator weist den Mikrocontroller an, den Wert oder Ausdruck auf der rechten Seite des Gleichheitszeichens auszuwerten und in der Variablen links vom Gleichheitszeichen zu speichern.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode



[source,arduino]
----
int sensVal;              // Deklarieren einer Integer-Variable mit dem Namen sensVal
sensVal = analogRead(0);  // Speichern der (digitalisierten) Eingangsspannung am Analogpin 0 in sensVal
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
1. Die Variable auf der linken Seite des Zuweisungsoperators (= Zeichen) muss den darin gespeicherten Wert enthalten können. Wenn er nicht groß genug ist, um einen Wert zu speichern, ist der in der Variablen gespeicherte Wert falsch.

2. Verwechseln Sie den Zuweisungsoperator [=] (einfaches Gleichheitszeichen) nicht mit dem Vergleichsoperator [==] (doppelte Gleichheitszeichen), der bewertet, ob zwei Ausdrücke gleich sind.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE#  link:../../control-structure/if[if (conditional operators)]
* #SPRACHE#  link:../../../variables/data-types/char[char]
* #SPRACHE#  link:../../../variables/data-types/int[int]
* #SPRACHE#  link:../../../variables/data-types/long[long]

--
// SEE ALSO SECTION ENDS
