---
title: "/"
title_expanded: "division"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---





= / Division


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
*Division* ist eine der vier primären Rechenoperationen. Der Operator `/` (Schrägstrich) bearbeitet zwei Operanden, um das Ergebnis zu erzeugen.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
result = numerator / denominator;
----

[float]
=== Parameter
`result` : Variable. *Erlaubte Datentypen:* int, float, double, byte, short, long  +
`numerator` : Variable oder Konstante. *Erlaubte Datentypen:* int, float, double, byte, short, long  +
`denominator` : *Nicht null* Variable oder Konstante. *Erlaubte Datentypen:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int a = 50;
int b = 10;
int c = 0;
c = a / b; // Die Variable 'c' erhält einen Wert von 5, nachdem diese Anweisung ausgeführt wurde
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
1. Wenn eine der Zahlen (Operanden) vom Typ float oder vom Typ double ist, wird für die Berechnung Fließkomma-Mathematik verwendet.

2. Wenn die Operanden vom Datentyp float / double sind und die Variable, die die Summe speichert, eine Ganzzahl ist, wird nur die Ganzzahl gespeichert und der Bruchteil der Zahl geht verloren.

[source,arduino]
----
float a = 55.5;
float b = 6.6;
int c = 0;
c = a / b; // Die Variable 'c' speichert nur den Wert 8 im Gegensatz zum erwarteten Ergebnis von 8,409
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
