---
title: "%"
title_expanded: Modulo
categories: [ "Structure" ]
subCategories: [ "Arithmetische Operatoren" ]
---





= % Modulo


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Die Operation *Modulo* berechnet den Rest, wenn eine ganze Zahl durch eine andere geteilt wird.
Dies ist nützlich, um eine Variable innerhalb eines bestimmten Bereichs zu halten (z. B. die Größe eines Arrays).
Das `%` (Prozent) -Symbol wird zur Ausführung der Modulo-Operation verwendet.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
remainder = dividend % divisor;
----

[float]
=== Parameter
`remainder`: Variable. *Erlaubte Datentypen:* int, float, double +
`dividend`: Variable oder Konstante. *Erlaubte Datentypen:* int +
`divisor`: *Nicht null* Variable oder Konstante. *Erlaubte Datentypen:* int
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int x = 0;
x = 7 % 5;    // x enthält jetzt 2
x = 9 % 5;    // x enthält jetzt 4
x = 5 % 5;    // x enthält jetzt 0
x = 4 % 5;    // x enthält jetzt 4
----

[source,arduino]
----
/* Aktualisieren eines Werts in einem Array durch eine Schleife */

int values[10];
int i = 0;

void setup() {}

void loop()
{
  values[i] = analogRead(0);
  i = (i + 1) % 10;   // Modulo-Operator überschreibt Variable
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Der Modulo-Operator arbeitet nicht mit float-Werten.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
