---
title: "*"
title_expanded: "multiplication"
categories: [ "Structure" ]
subCategories: [ "Arithmetische Operatoren" ]
---





= * Multiplication


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
*Multiplikation* ist eine der vier primären Rechenoperationen. Der Operator `*` (Sternchen) bearbeitet zwei Operanden, um das Produkt zu erzeugen.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
product = operand1 * operand2;
----

[float]
=== Parameter
`product` : Variable. *Erlaubte Datentypen:* int, float, double, byte, short, long  +
`operand1` : Variable oder Konstante. *Erlaubte Datentypen:* int, float, double, byte, short, long  +
`operand2` : Variable oder Konstante. *Erlaubte Datentypen:* int, float, double, byte, short, long
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int a = 5;
int b = 10;
int c = 0;
c = a * b; // Die Variable 'c' erhält einen Wert von 50, nachdem diese Anweisung ausgeführt wurde
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
1. Die Multiplikationsoperation kann überlaufen, wenn das Ergebnis größer ist als das, welches im Datentyp gespeichert werden kann.

2. Wenn eine der Zahlen (Operanden) vom Typ float oder vom Typ double ist, wird für die Berechnung Fließkomma-Mathematik verwendet.

3. Wenn die Operanden vom Datentyp float / double sind und die Variable, in der das Produkt gespeichert wird, eine ganze Zahl ist, wird nur die Ganzzahl gespeichert und der Bruchteil der Zahl geht verloren.

[source,arduino]
----
float a = 5.5;
float b = 6.6;
int c = 0;
c = a * b; // Die Variable 'c' speichert nur den Wert 36 und nicht das erwartete Produkt 36,3
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
