---
title: "-"
title_expanded: Subtraktion
categories: [ "Structure" ]
subCategories: [ "Arithmetische Operatoren" ]
---





= - Subtraktion


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
*Subtraktion* ist eine der vier primären Rechenoperationen. Der Operator `-` (minus) verarbeitet zwei Operanden, um die Differenz des zweiten zum ersten zu erzeugen.
[%hardbreaks]


[float]
=== Syntax
`difference = operand1 - operand2`


[float]
=== Parameter
`difference`: Variable. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long` +
`operand1`: Variable oder Konstante. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long` +
`operand2`: Variable oder Konstante. Erlaubte Datentypen: `int`, `float`, `double`, `byte`, `short`, `long`


--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode

[source,arduino]
----
int a = 5;
int b = 10;
int c = 0;
c = a - b; // Die Variable 'c' erhält nach der Ausführung dieser Anweisung einen Wert von -5
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
1. Die Subtraktionsoperation kann überlaufen, wenn das Ergebnis kleiner als das ist, das in dem Datentyp gespeichert werden kann (z. B. ergibt das Subtrahieren von 1 von einer Ganzzahl mit dem Wert -32,768 den Wert 32,767).

2. Wenn eine der Zahlen (Operanden) vom Typ `float` oder vom Typ `double` ist, wird für die Berechnung Fließkomma-Mathematik verwendet.

3. Wenn die Operanden vom Datentyp `float` / `double` sind und die Variable, die die Differenz speichert, eine Ganzzahl ist, wird nur die Ganzzahl gespeichert und der Bruchteil der Zahl geht verloren.

[source,arduino]
----
float a = 5.5;
float b = 6.6;
int c = 0;
c = a - b; // Die Variable 'c' speichert nur den Wert -1 und nicht die erwartete Differenz von -1.1
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Siehe auch

[role="language"]

--
// SEE ALSO SECTION ENDS
