---
title: Serial.available()
---

= available()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Rufe die Anzahl der zum Lesen verfügbaren Bytes (Zeichen) von der seriellen Schnittstelle ab. Dies sind Daten, die bereits eingetroffen sind und im seriellen Empfangspuffer gespeichert sind (der 64 Byte enthält).

`_Serial_.available()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.available()`

[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Siehe die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].

[float]
=== Rückgabewert
Die Anzahl der zum Lesen verfügbaren Bytes.
--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄
Der folgende Code gibt ein Zeichen zurück, das über die serielle Schnittstelle empfangen wurde.

[source,arduino]
----
int incomingByte = 0; // Für eingehende serielle Daten

void setup() {
  Serial.begin(9600); // Öffnet die serielle Schnittstelle und stellt die Datenrate auf 9600 Bit/s ein
}

void loop() {
  // Antworten, wenn Daten erhalten werden:
  if (Serial.available() > 0) {
    // Lies das eingehende Byte:
    incomingByte = Serial.read();

    // Ausgabe:
    Serial.print("I received: ");
    Serial.println(incomingByte, DEC);
  }
}
----
[%hardbreaks]

*Arduino Mega Beispiel:*
Dieser Code sendet Daten, die über einen seriellen Port des Arduino Mega empfangen werden, an einen anderen.
Dies kann zum Beispiel verwendet werden, um ein serielles Gerät über das Arduino-Board an den Computer anzuschließen.

[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);
}

void loop() {
  // Von Port 0 lesen, an Port 1 senden:
  if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, DEC);
  }
  // Von Port 1 lesen, an Port 0 senden:
  if (Serial1.available()) {
    int inByte = Serial1.read();
    Serial.print(inByte, DEC);
  }
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../begin[begin()] +
* #SPRACHE# link:../end[end()] +
* #SPRACHE# link:../read[read()] +
* #SPRACHE# link:../peek[peek()] +
* #SPRACHE# link:../flush[flush()] +
* #SPRACHE# link:../print[print()] +
* #SPRACHE# link:../println[println()] +
* #SPRACHE# link:../write[write()] +
* #SPRACHE# link:../serialevent[SerialEvent()] +
* #SPRACHE# link:../../stream/streamavailable[Stream.available()]

--
// SEE ALSO SECTION ENDS
