---
title: Serial.begin()
---




= begin()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Legt die Datenrate in Bit pro Sekunde (Baud) für die serielle Datenübertragung fest. Verwende für die Kommunikation mit dem seriellen Monitor eine der im Menü in der rechten unteren Ecke des Bildschirms aufgeführten Baudraten.
Du kannst aber andere Raten angeben, z. B. um über die Pins 0 und 1 mit einer Komponente zu kommunizieren, die eine bestimmte Baudrate erfordert.

Ein optionales zweites Argument konfiguriert die Daten-, Paritäts- und Stoppbits. Der Standardwert ist 8 Datenbits, keine Parität, ein Stoppbit.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.begin(speed)` +
`_Serial_.begin(speed, config)`



[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].

`speed`: In Bits pro Sekunde (Baud) - `long`

`config`: Setzt Daten, Parität und Stoppbits. Gültige Werte sind:

`SERIAL_5N1` +
`SERIAL_6N1` +
`SERIAL_7N1` +
`SERIAL_8N1` (the default) +
`SERIAL_5N2` +
`SERIAL_6N2` +
`SERIAL_7N2` +
`SERIAL_8N2` +
`SERIAL_5E1` +
`SERIAL_6E1` +
`SERIAL_7E1` +
`SERIAL_8E1` +
`SERIAL_5E2` +
`SERIAL_6E2` +
`SERIAL_7E2` +
`SERIAL_8E2` +
`SERIAL_5O1` +
`SERIAL_6O1` +
`SERIAL_7O1` +
`SERIAL_8O1` +
`SERIAL_5O2` +
`SERIAL_6O2` +
`SERIAL_7O2` +
`SERIAL_8O2` +

[float]
=== Rückgabewert
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und fügen Sie relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
void setup() {
    Serial.begin(9600); // Öffnet die serielle Schnittstelle und stellt die Datenrate auf 9600 Bit/s ein
}

void loop() {}
----
[%hardbreaks]

*Arduino Mega Beispiel:*
[source,arduino]
----
// Arduino Mega verwendet alle vier seriellen Anschlüsse
// (Serial, Serial1, Serial2, Serial3),
// mit unterschiedlichen Baudraten:

void setup() {
  Serial.begin(9600);
  Serial1.begin(38400);
  Serial2.begin(19200);
  Serial3.begin(4800);

  Serial.println("Hello Computer");
  Serial1.println("Hello Serial 1");
  Serial2.println("Hello Serial 2");
  Serial3.println("Hello Serial 3");
}
void loop() {}
----
[%hardbreaks]
Danke an Jeff Gray für das Mega-Beispiel


[float]
=== Anmerkungen und Warnungen
Bei seriellen USB-CDC-Anschlüssen (z. B. `Serial` am Leonardo) ist `Serial.begin()` irrelevant. Du kannst eine beliebige Baudrate und Konfiguration für die serielle Kommunikation mit diesen Ports verwenden.
Siehe die Liste der verfügbaren seriellen Schnittstellen für jedes Board auf der link:../../serial[Serial-Hauptseite].
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
