---
title: Serial.findUntil()
---




= Serial.findUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`Serial.findUntil()` liest Daten aus dem seriellen Puffer, bis eine Zielzeichenfolge mit einer angegebenen Länge oder Terminatorzeichenfolge gefunden wird.

Die Funktion gibt `true` zurück, wenn die Zielzeichenfolge gefunden wird, `false`, wenn das Zeitlimit überschritten wird.

`Serial.findUntil()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.findUntil(target, terminal)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`target` : Die Zeichenfolge, nach der gesucht werden soll (`char`) +
`terminal` : Die Terminalzeichenfolge bei der Suche (`char`)

[float]
=== Rückgabewert
`bool`

--
// OVERVIEW SECTION ENDS

// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[stream] +
* #SPRACHE# link:../../stream/streamfinduntil[stream.findUntil()]

--
// SEE ALSO SECTION ENDS
