---
title: Serial.find()
---




= Serial.find()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`Serial.find()` liest Daten aus dem seriellen Puffer, bis das Ziel gefunden wurde. Die Funktion gibt `true` zurück, wenn ein Ziel gefunden wurde, und `false`, wenn das Zeitlimit überschritten wird.

`Serial.find()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.find(target)` +
`_Serial_.find(target, length)`

[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].

`target` : Die Zeichenfolge, nach der gesucht werden soll (`char`)

`length` : Länge des Ziels (`size_t`)

[float]
=== Rückgabewert
`bool`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[stream] +
* #SPRACHE# link:../../stream/streamfind[stream.find()]

--
// SEE ALSO SECTION ENDS
