---
title: Serial.find()
---




= Serial.find()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`_Serial_.find()` liest Daten aus dem seriellen Puffer, bis das Ziel gefunden wurde. Die Funktion gibt `true` zurück, wenn ein Ziel gefunden wurde, und `false`, wenn das Zeitlimit überschritten wird.

`_Serial_.find()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.find(target)` +
`_Serial_.find(target, length)`

[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`target`: Die Zeichenfolge, nach der gesucht werden soll. Erlaubte Datentypen: `char`. +
`length`: Länge des Ziels. Erlaubte Datentypen: `size_t`.

[float]
=== Rückgabewert
Datentyp: `bool`.

--
// ÜBERSICHTSABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[stream] +
* #SPRACHE# link:../../stream/streamfind[stream.find()]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
