---
title: if(Serial)
---




= if (Serial)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Gibt an, ob der angegebene serielle Port bereit ist.

Auf den Boards mit nativem USB-Anschluss zeigt `if (Serial)` (oder `if (SerialUSB)` auf dem Due) an, ob die serielle USB-CDC-Verbindung geöffnet ist.
Bei allen anderen Boards und den Nicht-USB-CDC-Anschlüssen wird immer `true` zurückgegeben.

Dies wurde in Arduino IDE 1.0.1 eingeführt.
[%hardbreaks]


[float]
=== Syntax
`if (Serial)`


[float]
=== Parameter
Keine.


[float]
=== Rückgabewert
Gibt `true` zurück, wenn der angegebene serielle Port verfügbar ist. Dies gibt nur dann `false` zurück, wenn die serielle USB-CDC-Verbindung des Leonardos abgefragt wird, bevor sie fertig ist. Datentyp: `bool`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
void setup() {
  // Serielle Schnittstelle initialisieren und warten, bis der Port geöffnet ist:
  Serial.begin(9600);
  while (!Serial) {
    ; // Warte, bis die serielle Schnittstelle verbunden ist. Wird für native USBs benötigt.
  }
}

void loop() {
  // Normal weitermachen
}
----

--
// HOW TO USE SECTION ENDS
