---
title: Serial.parseInt()
---




= parseInt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Sucht nach der nächsten gültigen Ganzzahl in der eingehenden Seriennummer. Die Funktion wird abgebrochen, wenn eine Zeitüberschreitung auftritt (siehe link:../settimeout[Serial.setTimeout()]).

`Serial.parseInt()` erbt von der link:../../stream[Stream]-Dienstklasse.

Genauer gesagt:

* Die Analyse stoppt, wenn für einen konfigurierbaren Timeout-Wert keine Zeichen gelesen wurden oder eine Nicht-Ziffer gelesen wird; +
* Wenn beim Timeout (siehe link:../settimeout[Serial.setTimeout()]) keine gültigen Ziffern gelesen wurden, wird 0 zurückgegeben.
[%hardbreaks]


[float]
=== Syntax
`Serial.parseInt()` +
`Serial.parseInt(lookahead)` +
`Serial.parseInt(lookahead, ignore)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Schnittstellen für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`lookahead`: Der Modus, mit dem im Stream nach vorne nach einer Ganzzahl gesucht wird. Erlaubte Datentypen: `LookaheadMode`.
Erlaubte `lookahead`-Werte:

* `SKIP_ALL`: Alle Zeichen außer Ziffern oder einem Minuszeichen werden beim Scannen des Streams nach einer Ganzzahl ignoriert. Dies ist der Standardmodus.
* `SKIP_NONE`: Nichts wird übersprungen und der Stream wird nur dann berührt, wenn das erste wartende Zeichen gültig ist.
* `SKIP_WHITESPACE`: Nur Registerkarten, Leerzeichen, Zeilenvorschub und Carriage Returns werden übersprungen.

`ignore`: Wird verwendet, um das angegebene Zeichen bei der Suche zu überspringen. Wird beispielsweise verwendet, um Tausenderteiler zu überspringen. Zulässige Datentypen: `char`

[float]
=== Rückgabewert
`long` : Die nächste gültige ganze Zahl

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../begin[begin()] +
* #SPRACHE# link:../end[end()] +
* #SPRACHE# link:../available[available()] +
* #SPRACHE# link:../read[read()] +
* #SPRACHE# link:../peek[peek()] +
* #SPRACHE# link:../flush[flush()] +
* #SPRACHE# link:../print[print()] +
* #SPRACHE# link:../println[println()] +
* #SPRACHE# link:../write[write()] +
* #SPRACHE# link:../serialevent[SerialEvent()] +
* #SPRACHE# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
