---
title: Serial.parseFloat()
---




= Serial.parseFloat()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`Serial.parseFloat()` gibt die erste gültige Gleitkommazahl aus dem seriellen Puffer zurück. Zeichen, die keine Ziffern (oder das Minuszeichen) sind, werden übersprungen.
`parseFloat()` wird durch das erste Zeichen beendet, das keine Fließkommazahl ist. Die Funktion wird abgebrochen, wenn eine Zeitüberschreitung auftritt (siehe link:../settimeout[Serial.setTimeout()]).

`Serial.parseFloat()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.parseFloat()`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].

[float]
=== Gibt zurück
`float`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[stream()]
* #SPRACHE# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
