---
title: Serial.peek()
---




= peek()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Gibt das nächste Byte (Zeichen) eingehender serieller Daten zurück, ohne sie aus dem internen seriellen Puffer zu entfernen.
Das bedeutet, dass aufeinanderfolgende Aufrufe von `peek()` dasselbe Zeichen zurückgeben wie der nächste Aufruf von `read()`.

`_Serial_.peek()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.peek()`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].


[float]
=== Rückgabewert
Das erste verfügbare Byte der eingehenden seriellen Daten (oder -1, wenn keine Daten verfügbar sind). Datentyp: `int`.

--
// ÜBERSICHTSABSCHNITT ENDET


// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../begin[begin()] +
* #SPRACHE# link:../end[end()] +
* #SPRACHE# link:../available[available()] +
* #SPRACHE# link:../read[read()] +
* #SPRACHE# link:../peek[peek()] +
* #SPRACHE# link:../flush[flush()] +
* #SPRACHE# link:../print[print()] +
* #SPRACHE# link:../println[println()] +
* #SPRACHE# link:../write[write()] +
* #SPRACHE# link:../serialevent[SerialEvent()] +
* #SPRACHE# link:../../stream/streampeek[Stream.peek()]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
