---
title: Serial.peek()
---




= peek()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Returns the next byte (character) of incoming serial data without removing it from the internal serial buffer. That is, successive calls to `peek()` will return the same character, as will the next call to `read()`.

`Serial.peek()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.peek()`


[float]
=== Parameters
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page].

[float]
=== Returns
The first byte of incoming serial data available (or -1 if no data is available) - `int`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #SPRACHE# link:../begin[begin()] +
* #SPRACHE# link:../end[end()] +
* #SPRACHE# link:../available[available()] +
* #SPRACHE# link:../read[read()] +
* #SPRACHE# link:../peek[peek()] +
* #SPRACHE# link:../flush[flush()] +
* #SPRACHE# link:../print[print()] +
* #SPRACHE# link:../println[println()] +
* #SPRACHE# link:../write[write()] +
* #SPRACHE# link:../serialevent[SerialEvent()] +
* #SPRACHE# link:../../stream/streampeek[Stream.peek()]

--
// SEE ALSO SECTION ENDS
