---
title: Serial.println()
---




= println()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Druckt Daten an den seriellen Anschluss als von Menschen lesbarer ASCII-Text, gefolgt von einem Carriage-Return (ASCII 13 oder '\r') und einem Zeilenvorschubzeichen (ASCII 10 oder '\n').
Dieser Befehl hat die gleiche Form wie link:../print[Serial.print()].
[%hardbreaks]


[float]
=== Syntax
`_Serial_.println(val)` +
`_Serial_.println(val, format)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`val`: Der zu druckende Wert. Erlaubte Datentypen: Beliebiger Datentyp. +
`format`: Gibt die Basis (für ganzzahlige Datentypen) oder die Anzahl der Dezimalstellen (für Gleitkommatypen) an.


[float]
=== Rückgabewert
Gibt die Anzahl der geschriebenen Bytes zurück, das Lesen dieser Anzahl ist jedoch optional. Datentyp: `size_t`.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
/*
 Analogeingang liest einen analogen Eingang in 0 und druckt den Wert aus.
 Erstellt am 24. März 2006
 von Tom Igoe
 */

int analogValue = 0;    // Variable für den analogen Wert

void setup() {
  // Öffne die serielle Schnittstelle bei 9600 Bit/s:
  Serial.begin(9600);
}

void loop() {
  // Lies den Analogeingang an Pin 0:
  analogValue = analogRead(0);

  // print it out in many formats:
  Serial.println(analogValue);       // Drucken als ASCII-codierte Dezimalzahl
  Serial.println(analogValue, DEC);  // Drucken als ASCII-codierte Dezimalzahl
  Serial.println(analogValue, HEX);  // Drucken als ASCII-codierte Hexadezimalzahl
  Serial.println(analogValue, OCT);  // Drucken als ASCII-codierte Oktalzahl
  Serial.println(analogValue, BIN);  // Drucken als ASCII-codierte Binärzahl

  // Verzögerung 10 Millisekunden vor der nächsten Ablesung:
  delay(10);
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Informationen zur Asynchronität von `_Serial_.println()` findest du im Abschnitt Hinweise und Warnungen von link:../write#howtouse[Serial.write()].

--
// HOW TO USE SECTION ENDS
