---
title: Serial.readString()
---




= readString()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`_Serial_.readString()` liest Zeichen aus dem seriellen Puffer in einen String. Die Funktion wird abgebrochen, wenn eine Zeitüberschreitung auftritt (siehe link:../settimeout[setTimeout()]).

`_Serial_.readString()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.readString()`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].


[float]
=== Rückgabewert
Ein `String`, der aus dem seriellen Puffer gelesen wird.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../serial[Serial]
* #SPRACHE# link:../begin[begin()]
* #SPRACHE# link:../end[end()]
* #SPRACHE# link:../available[available()]
* #SPRACHE# link:../read[read()]
* #SPRACHE# link:../peek[peek()]
* #SPRACHE# link:../flush[flush()]
* #SPRACHE# link:../print[print()]
* #SPRACHE# link:../println[println()]
* #SPRACHE# link:../write[write()]
* #SPRACHE# link:../serialevent[SerialEvent()]
* #SPRACHE# link:../parsefloat[parseFloat()]

--
// SEE ALSO SECTION ENDS
