---
title: Serial.readBytesUntil()
---




= Serial.readBytesUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`_Serial_.readBytesUntil()` liest Zeichen aus dem seriellen Puffer in ein Array.
Die Funktion wird beendet, wenn das Abschlusszeichen erkannt wird, die ermittelte Länge gelesen wurde oder das Zeitlimit überschritten wurde (siehe link:../settimeout[Serial.setTimeout()]).
Die Funktion gibt die Zeichen bis zum letzten Zeichen vor dem angegebenen Abschluss zurück. Das Terminatorzeichen selbst wird nicht im Puffer zurückgegeben.

`_Serial_.readBytesUntil()` gibt die Anzahl der in den Puffer eingelesenen Zeichen zurück. Eine 0 bedeutet, dass keine gültigen Daten gefunden wurden.

`_Serial_.readBytesUntil()` erbt von der link:../../stream [Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.readBytesUntil(character, buffer, length)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`character`: Das zu suchende Zeichen. Erlaubte Datentypen: `char`. +
`buffer`: Der Puffer zum Speichern der Bytes. Erlaubte Datentypen: Array von `char` oder `byte`. +
`length`: Die Anzahl der zu lesenden Bytes. Erlaubte Datentypen: `int`. +

[float]
=== Rückgabewert
`size_t`

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Das Abschlusszeichen wird aus dem seriellen Puffer gelöscht.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[Stream]
* #SPRACHE# link:../../stream/streamreadbytesuntil[Stream.readBytesUntil()]

--
// SEE ALSO SECTION ENDS
