---
title: Serial.readBytes()
---




= Serial.readBytes()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`_Serial_.readBytes()` liest Zeichen vom seriellen Port in einen Puffer. Die Funktion wird beendet, wenn die ermittelte Länge gelesen wurde oder das Zeitlimit überschritten wurde (siehe link:../settimeout[Serial.setTimeout()]).

`_Serial_.readBytes()` gibt die Anzahl der Zeichen in den Puffer zurück. Eine 0 bedeutet, dass keine gültigen Daten gefunden wurden.

`_Serial_.readBytes()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.readBytes(buffer, length)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].

`buffer`: Der Puffer zum Speichern der Bytes (`char[]` oder `byte[]`)

`length` : Die Anzahl der zu lesenden Bytes (`int`)

[float]
=== Rückgabewert
Die Anzahl der Bytes, die im Puffer abgelegt wurden (`size_t`)

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[stream]
* #SPRACHE# link:../../stream/streamreadbytes[stream.readBytes()]

--
// SEE ALSO SECTION ENDS
