---
title: Serial.readStringUntil()
---




= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
`readStringUntil()` liest Zeichen aus dem seriellen Puffer in einen String. Die Funktion wird abgebrochen, wenn eine Zeitüberschreitung auftritt (siehe link:../settimeout[setTimeout()]).

Diese Funktion ist Teil der Stream-Klasse und wird von jeder Klasse aufgerufen, die von ihr erbt (Wire, Serial usw.). Siehe die link:../../stream[Stream-Klasse] für weitere Informationen.

[%hardbreaks]


[float]
=== Syntax
`_Serial_.readStringUntil(terminator)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`terminator`: Das zu suchende Zeichen. Erlaubte Datentypen: `char`.


[float]
=== Rückgabewert
Der gesamte `String`, der vom seriellen Puffer bis zum Abschlusszeichen gelesen wird.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Das Abschlusszeichen wird aus dem seriellen Puffer gelöscht.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../serial[Serial]
* #SPRACHE# link:../begin[begin()]
* #SPRACHE# link:../end[end()]
* #SPRACHE# link:../available[available()]
* #SPRACHE# link:../read[read()]
* #SPRACHE# link:../peek[peek()]
* #SPRACHE# link:../flush[flush()]
* #SPRACHE# link:../print[print()]
* #SPRACHE# link:../println[println()]
* #SPRACHE# link:../write[write()]
* #SPRACHE# link:../serialevent[SerialEvent()]
* #SPRACHE# link:../../stream/streamparsefloat[stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
