---
title: serialEvent()
---




= serialEvent()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Wird aufgerufen, wenn Daten verfügbar sind. Verwende `_Serial_.read()`, um diese Daten zu erfassen.
[%hardbreaks]


[float]
=== Syntax

[source,arduino]
----
void serialEvent() {
   // Statement(s)
}
----
Für Boards mit zusätzlichen seriellen Anschlüssen (siehe Liste der verfügbaren seriellen Anschlüsse für jede Karte auf der link:../../serial[Serial-Hauptseite]):
[source,arduino]
----
void serialEvent1() {
   // Statement(s)
}

void serialEvent2() {
   // Statement(s)
}

void serialEvent3() {
   // Statement(s)
}
----


[float]
=== Parameter
`Statement(s)`: Alle gültigen Aussagen.


[float]
=== Rückgabewert
Nichts.

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
`serialEvent()` funktioniert nicht mit dem Leonardo, Micro oder Yún.

`serialEvent()` und `serialEvent1()` funktionieren nicht auf den Arduino-SAMD-Boards.

`serialEvent()`, `serialEvent1()`, `serialEvent2()`, und `serialEvent3()` funktionieren nicht auf dem Arduino Due.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="example"]
* #BEISPIEL# http://arduino.cc/en/Tutorial/SerialEvent[Serielle Events^]

[role="language"]
* #SPRACHE# link:../begin[begin()]
* #SPRACHE# link:../end[end()]
* #SPRACHE# link:../available[available()]
* #SPRACHE# link:../read[read()]
* #SPRACHE# link:../peek[peek()]
* #SPRACHE# link:../flush[flush()]
* #SPRACHE# link:../print[print()]
* #SPRACHE# link:../println[println()]
* #SPRACHE# link:../write[write()]

--
// SEE ALSO SECTION ENDS
