---
title: Serial.setTimeout()
---




= Serial.setTimeout()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
`_Serial_.setTimeout()` legt die maximalen Millisekunden für das Warten auf serielle Daten fest. Der Standardwert ist 1000 Millisekunden.

`_Serial_.setTimeout()` erbt von der link:../../stream[Stream]-Dienstklasse.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.setTimeout(time)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`time`: Timeout-Dauer in Millisekunden. Erlaubte Datentypen: `long`.


[float]
=== Rückgabewert
Nichts.

--
// ÜBERSICHTSABSCHNITT ENDET

// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Serielle Funktionen, die den eingestellten Timeout-Wert verwenden `_Serial_.setTimeout()`:

* `_Serial_.find()`
* `_Serial_.findUntil()`
* `_Serial_.parseInt()`
* `_Serial_.parseFloat()`
* `_Serial_.readBytes()`
* `_Serial_.readBytesUntil()`
* `_Serial_.readString()`
* `_Serial_.readStringUntil()`

[%hardbreaks]

--
// HOW-TO-USE-ABSCHNITT ENDET

// SIEHE-AUCH-ABSCHNITT SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #SPRACHE# link:../../stream[stream]
* #SPRACHE# link:../../stream/streamsettimeout[stream.setTimeout()]

--
// SIEHE-AUCH-ABSCHNITT SECTION ENDET
