---
title: Serial.write()
---

= write()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Schreibt binäre Daten an die serielle Schnittstelle. Diese Daten werden als ein Byte oder eine Reihe von Bytes gesendet.
Zum Senden der Zeichen, die die Ziffern einer Zahl darstellen, verwende die link:../print[print()]-Funktion.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.write(val)` +
`_Serial_.write(str)` +
`_Serial_.write(buf, len)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite].

`val`: Ein Wert, der als einzelnes Byte gesendet werden soll

`str`: Eine Zeichenfolge, die als Folge von Bytes gesendet werden soll

`buf`: Ein Array, das als Folge von Bytes gesendet werden soll

`len`: Die Anzahl der Bytes, die vom Array gesendet werden sollen

[float]
=== Gibt zurück
`size_t`

`write()` gibt die Anzahl der geschriebenen Bytes zurück, das Lesen dieser Anzahl ist jedoch optional

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht und fügen Sie relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
void setup(){
  Serial.begin(9600);
}

void loop(){
  Serial.write(45); // Ein Byte mit dem Wert 45 senden

  int bytesSent = Serial.write(“hello”); // Sendet die Zeichenfolge "Hallo" und gibt die Länge der Zeichenfolge zurück.
}
----

--
// HOW TO USE SECTION ENDS
