---
title: Serial.write()
---

= write()


// ÜBERSICHTSABSCHNITT STARTET
[#overview]
--

[float]
=== Beschreibung
Schreibt binäre Daten an die serielle Schnittstelle. Diese Daten werden als ein Byte oder eine Reihe von Bytes gesendet.
Zum Senden der Zeichen, die die Ziffern einer Zahl darstellen, verwende die link:../print[print()]-Funktion.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.write(val)` +
`_Serial_.write(str)` +
`_Serial_.write(buf, len)`


[float]
=== Parameter
`_Serial_`: Serielles Port-Objekt. Die Liste der verfügbaren seriellen Anschlüsse für jedes Board auf der link:../../serial[Serial-Hauptseite]. +
`val`: Ein Wert, der als einzelnes Byte gesendet werden soll. +
`str`: Eine Zeichenfolge, die als Folge von Bytes gesendet werden soll. +
`buf`: Ein Array, das als Folge von Bytes gesendet werden soll. +
`len`: Die Anzahl der Bytes, die vom Array gesendet werden sollen.

[float]
=== Rückgabewert
Gibt die Anzahl der geschriebenen Bytes zurück, das Lesen dieser Anzahl ist jedoch optional. Datentyp: `size_t`.

--
// ÜBERSICHTSABSCHNITT ENDET




// HOW-TO-USE-ABSCHNITT STARTET
[#howtouse]
--
[float]
=== Beispielcode
// Beschreibe, worum es im Beispielcode geht, und füge relevanten Code hinzu   ►►►►► DIESER ABSCHNITT IST OBLIGATORISCH ◄◄◄◄◄


[source,arduino]
----
void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.write(45); // Sende ein Byte mit dem Wert 45

  int bytesSent = Serial.write("hello"); // Sende die Zeichenfolge "Hallo" und gib die Länge der Zeichenfolge zurück.
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Seit Arduino IDE 1.0 ist die serielle Übertragung asynchron. Wenn im Sendepuffer genügend freier Speicherplatz vorhanden ist, wird `_Serial_.write()` zurückgegeben, bevor Zeichen seriell übertragen werden.
Wenn der Sendepuffer voll ist, wird `_Serial_.write()` blockiert, bis im Puffer genügend Speicherplatz vorhanden ist.
Um das Blockieren von Aufrufen von `_Serial_.write()` zu vermeiden, kannst du zunächst den freien Speicherplatz im Sendepuffer mit überprüfen: link:../availableforwrite[availableForWrite()].

--
// HOW-TO-USE-ABSCHNITT ENDET
