---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= pulseIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Liest einen Wert von einem vorgegebenen Digitalpin ein, entweder `HIGH` oder `LOW`. Wenn *value* z.B. link:../../../variables/constants/constants/[HIGH] ist,
wartet `pulseIn()` darauf,dass der Pin auf den Wert link:../../../variables/constants/constants/[HIGH] wechselt, startet einen Timer und wartet anschließend darauf,
dass der Pin wieder auf link:../../../variables/constants/constants/[LOW] wechselt. Daraufhin stoppt `pulseIn()` den Timer. Gibt die Länge des Impulses in Mikrosekunden zurück.
Stoppt und gibt 0 zurück, wenn ein bestimmter Timeout erreicht wird.

Das Timing der Funktion wurde empirisch getestet und wird vermutlich bei einem längeren Impuls falsch messen. Die Funktion funtioniert mit Impulsen der Länge von 10 Mikrosekunden bis 3 Minuten.
[%hardbreaks]


[float]
=== Syntax
`pulseIn(pin, value)`

`pulseIn(pin, value, timeout)`

[float]
=== Parameter
`pin`: Die Pinnummer, an der der Impuls gelesen werden soll. (int)

`value`: Welche Art von Impuls gelesen werden soll: Entweder link:../../../variables/constants/constants/[HIGH] oder link:../../../variables/constants/constants/[LOW]. (int)

`timeout` (optional): Die Anzahl an Mikrosekunden, die gewartet werden soll, bis ein Impuls gemessen wurde; Default-Wert ist eine Sekunde (unsigned long)

[float]
=== Gibt zurück
Die Länge des Impulses (in Mikrosekunden) oder 0, wenn kein Impuls vor dem Timeout gemessen wird (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Das Beispiel gibt den Zeitraum eines Impulses auf Pin 7 aus.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  Serial.begin(9600);
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseIn(pin, HIGH);
  Serial.println(duration);
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
