---
title: pulseInLong()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= pulseInLong()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Liest einen Stromwert von einem Pin ein (entweder HIGH oder LOW). Wenn der *Wert* z.B. *HIGH* ist, wartet `pulseInLong()` darauf, dass der Pin auf den Wert *HIGH* wechselt, startet einen Timer und wartet anschließend darauf, dass der Pin wieder auf *LOW* wechselt. Daraufhin stoppt `pulseInLong()` den Timer. Gibt die Länge des Stromstoßes in Mikrosekunden zurück. Stoppt und gibt 0 zurück, wenn ein bestimmter Timeout erreicht wird.

Das Timing der Funktion wurde empirisch getestet und wird vermutlich bei längeren Stromstößen Fehler werfen. Die Funktion funtioniert mit einer Stromstößen der Länge von 10 Mikrosekunden bis 3 Minuten. Bitte beachte auch, dass, wenn ein Pin, der bereits *HIGH* ist, wenn die Funktion aufgerufen wird, zunächst auf *LOW* und dann wieder auf *HIGH* wechselt, bevor die Funktion startet. Diese Routine kann nur benutzt werden, wenn Interrupts aktiviert werden. Die beste Auflösung wird erreicht, wenn große Intervalle verwendet werden.
[%hardbreaks]


[float]
=== Syntax
`pulseInLong(pin, value)`

`pulseInLong(pin, value, timeout)`

[float]
=== Parameter
`pin`: Die Pinnummer, an der der Stromstoß gelesen werden soll. (int)

`value`: Welche Art von Stromstoß gelesen werden soll: Entweder link:../../../variables/constants/constants/[HIGH] oder link:../../../variables/constants/constants/[LOW]. (int)

`timeout` (optional): Die Anzahl an Mikrosekunden, die gewartet werden soll, bis ein Stromstoß gemessen wurde; Default-Wert ist eine Sekunde (unsigned long)
[float]
=== Gibt zurück
Die Länge des Stromstoßes (in Mikrosekunden) oder 0, wenn kein Stromstoß vor dem Timeout gemessen wird (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Das Beispiel gibt den Zeitraum eines Stromstoßes auf Pin 7 aus.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  Serial.begin(9600);
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseInLong(pin, HIGH);
  Serial.println(duration);
}
----
[%hardbreaks]

[float]
=== Anmerkungen und Warnungen
Diese Funktion verlässt sich auf `micros()` und kann somit in link:../../interrupts/nointerrupts[noInterrupts()] Kontexten nicht verwendet werden.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

--
// SEE ALSO SECTION ENDS
