---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= pulseIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Liest einen Stromwert von einem Pin ein (entweder HIGH oder LOW). Wenn der *Wert* z.B. *HIGH* ist, wartet `pulseIn()` darauf, dass der Pin auf den Wert *HIGH* wechselt, startet einen Timer und wartet anschließend darauf, dass der Pin wieder auf *LOW* wechselt. Daraufhin stoppt `pulseIn()` den Timer. Gibt die Länge des Stromstoßes in Mikrosekunden zurück. Stoppt und gibt 0 zurück, wenn ein bestimmter Timeout erreicht wird.

Das Timing der Funktion wurde empirisch getestet und wird vermutlich bei längeren Stromstößen Fehler werfen. Die Funktion funtioniert mit einer Stromstößen der Länge von 10 Mikrosekunden bis 3 Minuten.
[%hardbreaks]


[float]
=== Syntax
`pulseIn(pin, value)`

`pulseIn(pin, value, timeout)`

[float]
=== Parameter
`pin`: Die Pinnummer, an der der Stromstoß gelesen werden soll. (int)

`value`: Welche Art von Stromstoß gelesen werden soll: Entweder link:../../../variables/constants/constants/[HIGH] oder link:../../../variables/constants/constants/[LOW]. (int) 

`timeout` (optional): Die Anzahl an Mikrosekunden, die gewartet werden soll, bis ein Stromstoß gemessen wurde; Default-Wert ist eine Sekunde (unsigned long)
[float]

=== Gibt zurück
Die Länge des Stromstoßes (in Mikrosekunden) oder 0, wenn kein Stromstoß vor dem Timeout gemessen wird (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Beispielcode
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Das Beispiel errechnet den Zeitraum eines Stromstoßes auf Pin 7.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup()
{
  pinMode(pin, INPUT);
}

void loop()
{
  duration = pulseIn(pin, HIGH);
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
