---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Beschreibung
Generiert einen Ton mit der angegebenen Frequenz (und 50% duty cycle) auf einem Pin. Eine Dauer des Tons kann festgelegt werden; Sonst wird der Ton abgespielt, bis ein link:../noTone[noTone()] aufgerufen wird.
Der Pin kann an einen Piezo oder an einen Lautsprecher angeschlossen werden, um Töne abzuspielen.

Nur ein Ton kann gleichzeitig abgespielt werden. Wenn bereits ein Ton auf einem anderen Pin abgespielt wird, hat `tone()` auf einem 2. Pin keinen Effekt. Wenn der Ton auf dem gleichen Pin gespielt wird, setzt
der Aufruf der Funktion die Frequenz des Tons.

Die Nutzung der `tone()` Funktion interferiert mit PWM outputs auf Pin 3 und 11 (Auf Boards außer dem Arduino Mega).

Es ist nicht möglich, Töne mit einer Frequenz niedriger als 31Hz zu erstellen. Für technische Details, siehe https://github.com/bhagman/Tone#ugly-details[Brett Hagman's post].
[%hardbreaks]


[float]
=== Syntax
`tone(pin, frequency)`

`tone(pin, frequency, duration)`
[%hardbreaks]

[float]
=== Parameter
`pin`: Der Pin, auf dem der Ton generiert werden soll

`frequency`: Die Frequenz des Tons in Hertz (unsigned int)

`duration`: Die Dauer des Tons in Millisekunden (optional) (unsigned long)
[%hardbreaks]

[float]
=== Gibt zurück
Nichts

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Anmerkungen und Warnungen
Wenn du verschiedene Töne auf mehreren Pins spielen willst, musst du zunächst mit `noTone()` auf einem Pin den Ton stoppen und anschließend mit `tone()` auf dem nächsten Pin einen neuen Ton generieren.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Siehe auch

[role="language"]
* #LANGUAGE# link:../Analog%20IO/analogWrite.adoc[analogWrite()]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Töne^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Tonleiter^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Einfaches Keyboard^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[Mehrere Töne^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS